import type { HelpInventoryField } from "@/features/help/inventory/types";

/** Shared and module fields observed in admin UI. */
export const INVENTORY_FIELDS: HelpInventoryField[] = [
  {
    id: "field-meta-title",
    kind: "field",
    version: 1,
    label: "Meta title",
    description: "Page title shown in search results and browser tabs (locale-aware).",
  },
  {
    id: "field-meta-description",
    kind: "field",
    version: 1,
    label: "Meta description",
    description: "Short summary shown under the title in search results (locale-aware).",
  },
  {
    id: "field-focus-keywords",
    kind: "field",
    version: 1,
    label: "Focus keywords",
    description: "Primary keywords used for on-page SEO analysis.",
  },
  {
    id: "field-canonical-url",
    kind: "field",
    version: 1,
    label: "Canonical URL",
    description: "Preferred URL for duplicate or similar content.",
  },
  {
    id: "field-robots",
    kind: "field",
    version: 1,
    label: "Robots directives",
    description: "Index/follow combinations for search crawlers.",
  },
  {
    id: "field-og-title",
    kind: "field",
    version: 1,
    label: "OG title override",
    description: "Optional Open Graph title when sharing on social networks.",
  },
  {
    id: "field-og-image",
    kind: "field",
    version: 1,
    label: "Social image",
    description: "OG / social image selected via the media picker.",
  },
  {
    id: "field-twitter-card",
    kind: "field",
    version: 1,
    label: "Twitter card",
    description: "Large image or Summary card style for X/Twitter.",
  },
  {
    id: "field-json-ld",
    kind: "field",
    version: 1,
    label: "JSON-LD",
    description: "Structured data snippet for the page.",
  },
  {
    id: "field-coming-soon-toggle",
    kind: "field",
    version: 1,
    label: "Show coming soon page",
    description: "When enabled, visitors see Coming Soon instead of the public site.",
  },
  {
    id: "field-redirect-from",
    kind: "field",
    version: 1,
    label: "From path",
    description: "Source path for a redirect rule.",
  },
  {
    id: "field-redirect-to",
    kind: "field",
    version: 1,
    label: "To path",
    description: "Destination path for a redirect rule.",
  },
  {
    id: "field-redirect-type",
    kind: "field",
    version: 1,
    label: "Redirect type",
    description: "301 Permanent or 302 Temporary.",
  },
  {
    id: "field-robots-host",
    kind: "field",
    version: 1,
    label: "Host",
    description: "Optional host directive for robots.txt.",
  },
  {
    id: "field-robots-disallow",
    kind: "field",
    version: 1,
    label: "Additional disallow paths",
    description: "Extra disallow rules beyond built-in /admin/ and /api/.",
  },
  {
    id: "field-robots-allow",
    kind: "field",
    version: 1,
    label: "Additional allow paths",
    description: "Extra allow rules for robots.txt.",
  },
  {
    id: "field-sitemap-exclude",
    kind: "field",
    version: 1,
    label: "Exclude paths or URLs",
    description: "Paths/URLs omitted from the generated sitemap.",
  },
  {
    id: "field-sitemap-extra",
    kind: "field",
    version: 1,
    label: "Extra paths or URLs",
    description: "Manual additions included in the sitemap.",
  },
  {
    id: "field-locale-code",
    kind: "field",
    version: 1,
    label: "Locale code",
    description: "Language code for a site locale.",
  },
  {
    id: "field-locale-prefix",
    kind: "field",
    version: 1,
    label: "URL prefix",
    description: "Path prefix used on the public site for this locale.",
  },
  {
    id: "field-locale-direction",
    kind: "field",
    version: 1,
    label: "Direction",
    description: "LTR or RTL layout direction.",
  },
  {
    id: "field-indexnow-api-key",
    kind: "field",
    version: 1,
    label: "IndexNow API key",
    description:
      "Secret key (8–128 letters, numbers, or dashes) used to prove you own the site when submitting URLs to IndexNow (Bing, Yandex, Seznam, and others). The same value must appear in admin and in the public {key}.txt file.",
  },
  {
    id: "field-indexnow-endpoint",
    kind: "field",
    version: 1,
    label: "IndexNow endpoint",
    description:
      "API URL that receives URL submissions. Defaults to https://api.indexnow.org/indexnow when left blank.",
  },
  {
    id: "field-indexnow-key-location",
    kind: "field",
    version: 1,
    label: "IndexNow key location",
    description:
      "HTTPS URL of the verification text file. Must use the same host as live page URLs after redirects (on this site: https://brt-me.com/{key}.txt because www.brt-me.com redirects to brt-me.com). Leave blank to use that default.",
  },
];
