import type { HelpInventoryTab } from "@/features/help/inventory/types";

export const INVENTORY_TABS: HelpInventoryTab[] = [
  {
    id: "tab-seo-metadata-overview",
    kind: "tab",
    version: 1,
    label: "Overview",
    description: "Counts for CMS pages, blog posts, and static routes.",
  },
  {
    id: "tab-seo-metadata-global-tools",
    kind: "tab",
    version: 1,
    label: "Global tools",
    description: "Links to autofill, audits, redirects, robots, sitemap, and more.",
  },
  {
    id: "tab-seo-metadata-integrations",
    kind: "tab",
    version: 1,
    label: "Integrations & health",
    description: "Job metrics, provider health, and search analytics.",
  },
  {
    id: "tab-seo-metadata-static",
    kind: "tab",
    version: 1,
    label: "Static pages",
    description: "Page picker plus SeoMetaForm for static marketing routes.",
    componentIds: ["component-seo-meta"],
  },
  {
    id: "tab-pages-marketing",
    kind: "tab",
    version: 1,
    label: "Marketing Pages",
    description: "Wired marketing/slug pages list.",
  },
  {
    id: "tab-pages-cms",
    kind: "tab",
    version: 1,
    label: "CMS Pages",
    description: "Editable CMS pages list with New page.",
  },
  {
    id: "tab-translations-editor",
    kind: "tab",
    version: 1,
    label: "Editor",
    description: "Translation grid with filters and save.",
  },
  {
    id: "tab-translations-config",
    kind: "tab",
    version: 1,
    label: "Configuration",
    description: "AI translation provider settings.",
  },
  {
    id: "tab-theme-overview",
    kind: "tab",
    version: 1,
    label: "Overview",
  },
  {
    id: "tab-theme-presets",
    kind: "tab",
    version: 1,
    label: "Presets",
  },
  {
    id: "tab-theme-colors",
    kind: "tab",
    version: 1,
    label: "Colors",
  },
  {
    id: "tab-theme-typography",
    kind: "tab",
    version: 1,
    label: "Typography",
  },
  {
    id: "tab-theme-preview",
    kind: "tab",
    version: 1,
    label: "Preview",
  },
  {
    id: "tab-header-mobile",
    kind: "tab",
    version: 1,
    label: "Mobile",
  },
  {
    id: "tab-header-style",
    kind: "tab",
    version: 1,
    label: "Style",
  },
  {
    id: "tab-header-desktop",
    kind: "tab",
    version: 1,
    label: "Desktop",
  },
  {
    id: "tab-header-menus",
    kind: "tab",
    version: 1,
    label: "Menus",
  },
  {
    id: "tab-footer-sections",
    kind: "tab",
    version: 1,
    label: "Sections",
  },
  {
    id: "tab-footer-layout",
    kind: "tab",
    version: 1,
    label: "Layout",
  },
  {
    id: "tab-footer-design",
    kind: "tab",
    version: 1,
    label: "Design",
  },
  {
    id: "tab-seo-integrations-monitoring",
    kind: "tab",
    version: 1,
    label: "Monitoring",
  },
  {
    id: "tab-seo-integrations-configure",
    kind: "tab",
    version: 1,
    label: "Configure",
  },
  {
    id: "tab-seo-integrations-queue",
    kind: "tab",
    version: 1,
    label: "Queue & jobs",
  },
];
