export type SearchLocale = "en";

export const SEARCH_COPY = {
  en: {
    placeholder: "Search catalog, blog, pages, FAQs…",
    emptyTitle: "No results found",
    emptySub: "Try different keywords or clear filters.",
    startTitle: "Start typing to search",
    startSub: "Search across catalog, pages, posts, and more.",
    all: "All",
    search: "Search",
    suggestions: "Suggestions",
    results: "Results",
    recent: "Recent searches",
    popular: "Popular searches",
    trending: "Trending",
    history: "Search history",
    navigate: "↑↓ navigate",
    open: "↵ open",
    close: "esc close",
    typeMin: (n: number) => `Type at least ${n} characters for full results`,
    searching: "Searching…",
    pageTitle: "Search",
    pageSub: "Find pages, catalog items, collections, and blog posts.",
    resultCount: (n: number) => `${n} result${n === 1 ? "" : "s"}`,
    pressEnter: "Press Enter to search",
    clear: "Clear search",
    clearAllFilters: "Clear all filters",
    filtersActive: (n: number) => `${n} filter${n === 1 ? "" : "s"} active`,
    contentType: "Type",
    showMore: (n: number) => `Show ${n} more`,
    showLess: "Show less",
    searchError: "Search is temporarily unavailable. Try again.",
    tryRemovingFilters: "Try removing a filter or broadening your search.",
    loadMore: "Load more results",
    loadingMore: "Loading…",
    viewAllResults: (n: number) => `View all ${n}+ results`,
    relatedSearches: "Related",
    didYouMean: "Did you mean",
    filters: "Filters",
    openFilters: "Open filters",
    preview: "Preview",
    savedSearches: "Saved searches",
    saveSearch: "Save this search",
  },
} as const;

export function searchCopy(_locale?: string) {
  return SEARCH_COPY.en;
}
