import type { HelpChecklist } from "@/features/help/types";

export const HELP_CHECKLISTS: HelpChecklist[] = [
  {
    id: "checklist-launch",
    title: "Website Launch",
    summary: "Everything to verify before making the site public.",
    keywords: ["launch", "go live", "publish", "coming soon"],
    navItemIds: ["site-access", "pages"],
    items: [
      { id: "launch-logo", label: "Logo uploaded", href: "/admin/theme", navItemIds: ["theme"] },
      { id: "launch-header", label: "Header configured", href: "/admin/header", navItemIds: ["header"] },
      { id: "launch-footer", label: "Footer configured", href: "/admin/footer", navItemIds: ["footer"] },
      { id: "launch-home", label: "Home page published", href: "/admin/pages", navItemIds: ["pages"] },
      { id: "launch-contact", label: "Contact page ready", href: "/admin/pages", navItemIds: ["pages"] },
      { id: "launch-products", label: "Catalog content added", href: "/admin/products", navItemIds: ["products"] },
      { id: "launch-forms", label: "Forms tested", href: "/admin/forms", navItemIds: ["form-templates"] },
      { id: "launch-email", label: "Email notifications working", href: "/admin/settings/email-accounts", navItemIds: ["email-accounts"] },
      { id: "launch-mobile", label: "Mobile layout checked", href: "/admin/studio", navItemIds: ["studio"] },
      { id: "launch-seo", label: "SEO configured", href: "/admin/seo/setup", navItemIds: ["seo-overview"] },
      { id: "launch-sitemap", label: "Sitemap reviewed", href: "/admin/seo/sitemap", navItemIds: ["seo-sitemap"] },
      { id: "launch-robots", label: "Robots.txt reviewed", href: "/admin/seo/robots", navItemIds: ["seo-robots"] },
      { id: "launch-coming-soon", label: "Remove Coming Soon / open site", href: "/admin/settings/site", navItemIds: ["site-access"] },
    ],
  },
  {
    id: "checklist-multilingual",
    title: "Multilingual Checklist",
    summary: "Ship a complete bilingual (or multi-locale) experience.",
    keywords: ["language", "arabic", "english", "rtl", "translation", "locale"],
    navItemIds: ["languages", "translations"],
    items: [
      { id: "ml-en", label: "English locale enabled", href: "/admin/languages", navItemIds: ["languages"] },
      { id: "ml-ar", label: "Arabic (or second locale) enabled", href: "/admin/languages", navItemIds: ["languages"] },
      { id: "ml-translate", label: "Key pages translated", href: "/admin/translations", navItemIds: ["translations"] },
      { id: "ml-rtl", label: "RTL layout checked", href: "/admin/studio", navItemIds: ["studio"] },
      { id: "ml-switcher", label: "Language switcher visible", href: "/admin/header", navItemIds: ["header"] },
      { id: "ml-seo", label: "SEO fields translated", href: "/admin/seo", navItemIds: ["seo-overview"] },
    ],
  },
  {
    id: "checklist-store",
    title: "Store Checklist",
    summary: "Catalog readiness for product-led sites.",
    keywords: ["store", "products", "catalog", "inventory", "filters"],
    navItemIds: ["products"],
    featureFlags: ["catalog"],
    items: [
      { id: "store-taxonomy", label: "Brands & tags configured", href: "/admin/catalog-taxonomy", navItemIds: ["brands-tags"] },
      { id: "store-products", label: "Products added with images", href: "/admin/products", navItemIds: ["products"] },
      { id: "store-prices", label: "Prices set", href: "/admin/products", navItemIds: ["products"] },
      { id: "store-search", label: "Search indexes products", href: "/admin/settings/search", navItemIds: ["search-settings"] },
      { id: "store-collections", label: "Categories configured", href: "/admin/categories", navItemIds: ["categories"] },
    ],
  },
  {
    id: "checklist-seo-launch",
    title: "SEO Launch",
    summary: "Search visibility checks before go-live.",
    keywords: ["seo", "launch", "sitemap", "robots", "metadata"],
    navItemIds: ["seo-overview"],
    featureFlags: ["seo"],
    items: [
      { id: "seo-meta", label: "Homepage metadata set", href: "/admin/seo/metadata", navItemIds: ["seo-metadata"] },
      { id: "seo-sitemap", label: "Sitemap submitted in Google Search Console", href: "/admin/seo/sitemap", navItemIds: ["seo-sitemap"] },
      { id: "seo-robots", label: "Robots.txt reviewed", href: "/admin/seo/robots", navItemIds: ["seo-robots"] },
      { id: "seo-redirects", label: "Critical redirects checked", href: "/admin/seo/redirects", navItemIds: ["seo-redirects"] },
      {
        id: "seo-structured",
        label: "Structured data audited (missing fields fixed, GSC submitted)",
        href: "/admin/seo/structured-data?tab=audit",
        navItemIds: ["seo-structured-data"],
      },
      { id: "seo-google", label: "Google tools reviewed", href: "/admin/seo/google", navItemIds: ["seo-google"] },
      {
        id: "seo-indexing-api",
        label: "Google Indexing API configured (API enabled, SA Owner in GSC)",
        href: "/admin/seo/integrations?tab=configure&provider=google-indexing",
        navItemIds: ["seo-integrations"],
      },
      {
        id: "seo-indexnow",
        label: "IndexNow configured (key live at https://brt-me.com/{key}.txt, no www)",
        href: "/admin/seo/integrations?tab=configure&provider=indexnow",
        navItemIds: ["seo-integrations"],
      },
    ],
  },
  {
    id: "checklist-google-ads-setup",
    title: "Google Ads setup (SEO Google)",
    summary: "Connect under SEO → configure → sync Ad Accounts → link → scoreboard.",
    keywords: ["google ads", "oauth", "mcc", "campaign linking"],
    navItemIds: ["seo-google", "marketing-ad-accounts", "marketing-campaigns"],
    items: [
      {
        id: "ga-oauth-creds",
        label: "SEO Google OAuth client saved (Settings / global)",
        href: "/admin/seo/google?tab=settings",
        navItemIds: ["seo-google"],
      },
      {
        id: "ga-connect",
        label: "Google Ads OAuth connected (Ads tab)",
        href: "/admin/seo/google?tab=ads",
        navItemIds: ["seo-google"],
      },
      {
        id: "ga-dev-token",
        label: "Developer token saved on SEO Ads",
        href: "/admin/seo/google?tab=ads#configuration",
        navItemIds: ["seo-google"],
      },
      {
        id: "ga-mcc",
        label: "Numeric Manager Account (MCC) saved (not an email)",
        href: "/admin/seo/google?tab=ads#configuration",
        navItemIds: ["seo-google"],
      },
      {
        id: "ga-access",
        label: "Connect Google user has Admin/Standard access on that Ads customer",
        href: "/admin/seo/google?tab=ads",
        navItemIds: ["seo-google"],
      },
      {
        id: "ga-customer",
        label: "Ads customer configured & Ad Accounts synced (no 403)",
        href: "/admin/marketing/ad-accounts",
        navItemIds: ["marketing-ad-accounts"],
      },
      {
        id: "ga-link",
        label: "At least one Google campaign linked to a Marketing campaign",
        href: "/admin/marketing/campaigns",
        navItemIds: ["marketing-campaigns"],
      },
    ],
  },
  {
    id: "checklist-linkedin-ads-setup",
    title: "LinkedIn advertising connect",
    summary: "Developer app → redirect URI → credentials → Connect → verify.",
    keywords: ["linkedin", "linkedin ads", "oauth", "client id", "r_ads"],
    navItemIds: ["marketing-platforms", "marketing-tracking"],
    items: [
      {
        id: "li-app",
        label: "LinkedIn Developer app created with Ads / Marketing products enabled",
        href: "/admin/marketing/platforms?tab=linkedin",
        navItemIds: ["marketing-platforms"],
      },
      {
        id: "li-redirect",
        label: "Authorized redirect URL includes /api/marketing/oauth/linkedin/callback",
        href: "/admin/marketing/platforms?tab=linkedin",
        navItemIds: ["marketing-platforms"],
      },
      {
        id: "li-creds",
        label: "Client ID and Client Secret saved under Advertising Platforms → LinkedIn",
        href: "/admin/marketing/platforms?tab=linkedin",
        navItemIds: ["marketing-platforms"],
      },
      {
        id: "li-connect",
        label: "Connect LinkedIn completed (Connected status)",
        href: "/admin/marketing/platforms?tab=linkedin",
        navItemIds: ["marketing-platforms"],
      },
      {
        id: "li-partner",
        label: "Optional: LinkedIn Partner ID saved under Marketing → Tracking",
        href: "/admin/marketing/tracking",
        navItemIds: ["marketing-tracking"],
      },
    ],
  },
];
