import type { HelpChecklist } from "@/features/help/types";

export const HELP_CHECKLISTS: HelpChecklist[] = [
  {
    id: "checklist-launch",
    title: "Website Launch",
    summary: "Everything to verify before making the site public.",
    keywords: ["launch", "go live", "publish", "coming soon"],
    navItemIds: ["site-access", "pages"],
    items: [
      { id: "launch-logo", label: "Logo uploaded", href: "/admin/theme", navItemIds: ["theme"] },
      { id: "launch-header", label: "Header configured", href: "/admin/header", navItemIds: ["header"] },
      { id: "launch-footer", label: "Footer configured", href: "/admin/footer", navItemIds: ["footer"] },
      { id: "launch-home", label: "Home page published", href: "/admin/pages", navItemIds: ["pages"] },
      { id: "launch-contact", label: "Contact page ready", href: "/admin/pages", navItemIds: ["pages"] },
      { id: "launch-products", label: "Catalog content added", href: "/admin/products", navItemIds: ["products"] },
      { id: "launch-forms", label: "Forms tested", href: "/admin/forms", navItemIds: ["form-templates"] },
      { id: "launch-email", label: "Email notifications working", href: "/admin/settings/email-accounts", navItemIds: ["email-accounts"] },
      { id: "launch-mobile", label: "Mobile layout checked", href: "/admin/studio", navItemIds: ["studio"] },
      { id: "launch-seo", label: "SEO configured", href: "/admin/seo", navItemIds: ["seo-overview"] },
      { id: "launch-sitemap", label: "Sitemap reviewed", href: "/admin/seo/sitemap", navItemIds: ["seo-sitemap"] },
      { id: "launch-robots", label: "Robots.txt reviewed", href: "/admin/seo/robots", navItemIds: ["seo-robots"] },
      { id: "launch-coming-soon", label: "Remove Coming Soon / open site", href: "/admin/settings/site", navItemIds: ["site-access"] },
    ],
  },
  {
    id: "checklist-multilingual",
    title: "Multilingual Checklist",
    summary: "Ship a complete bilingual (or multi-locale) experience.",
    keywords: ["language", "arabic", "english", "rtl", "translation", "locale"],
    navItemIds: ["languages", "translations"],
    items: [
      { id: "ml-en", label: "English locale enabled", href: "/admin/languages", navItemIds: ["languages"] },
      { id: "ml-ar", label: "Arabic (or second locale) enabled", href: "/admin/languages", navItemIds: ["languages"] },
      { id: "ml-translate", label: "Key pages translated", href: "/admin/translations", navItemIds: ["translations"] },
      { id: "ml-rtl", label: "RTL layout checked", href: "/admin/studio", navItemIds: ["studio"] },
      { id: "ml-switcher", label: "Language switcher visible", href: "/admin/header", navItemIds: ["header"] },
      { id: "ml-seo", label: "SEO fields translated", href: "/admin/seo", navItemIds: ["seo-overview"] },
    ],
  },
  {
    id: "checklist-store",
    title: "Store Checklist",
    summary: "Catalog readiness for product-led sites.",
    keywords: ["store", "products", "catalog", "inventory", "filters"],
    navItemIds: ["products"],
    featureFlags: ["catalog"],
    items: [
      { id: "store-taxonomy", label: "Brands & tags configured", href: "/admin/catalog-taxonomy", navItemIds: ["brands-tags"] },
      { id: "store-products", label: "Products added with images", href: "/admin/products", navItemIds: ["products"] },
      { id: "store-prices", label: "Prices set", href: "/admin/products", navItemIds: ["products"] },
      { id: "store-search", label: "Search indexes products", href: "/admin/settings/search", navItemIds: ["search-settings"] },
      { id: "store-collections", label: "Categories configured", href: "/admin/categories", navItemIds: ["categories", "collections"] },
    ],
  },
  {
    id: "checklist-seo-launch",
    title: "SEO Launch",
    summary: "Search visibility checks before go-live.",
    keywords: ["seo", "launch", "sitemap", "robots", "metadata"],
    navItemIds: ["seo-overview"],
    featureFlags: ["seo"],
    items: [
      { id: "seo-meta", label: "Homepage metadata set", href: "/admin/seo/metadata", navItemIds: ["seo-metadata"] },
      { id: "seo-sitemap", label: "Sitemap reviewed", href: "/admin/seo/sitemap", navItemIds: ["seo-sitemap"] },
      { id: "seo-robots", label: "Robots.txt reviewed", href: "/admin/seo/robots", navItemIds: ["seo-robots"] },
      { id: "seo-redirects", label: "Critical redirects checked", href: "/admin/seo/redirects", navItemIds: ["seo-redirects"] },
      { id: "seo-structured", label: "Structured data readiness", href: "/admin/seo/structured-data", navItemIds: ["seo-structured-data"] },
      { id: "seo-google", label: "Google tools reviewed", href: "/admin/seo/google", navItemIds: ["seo-google"] },
    ],
  },
  {
    id: "checklist-forms-email",
    title: "Forms & Email Validation",
    summary: "Confirm lead capture and notifications work.",
    keywords: ["forms", "email", "smtp", "submissions"],
    navItemIds: ["form-templates", "email-accounts"],
    items: [
      { id: "fe-form", label: "Contact form published", href: "/admin/forms", navItemIds: ["form-templates"] },
      { id: "fe-email", label: "Email account configured", href: "/admin/settings/email-accounts", navItemIds: ["email-accounts"] },
      { id: "fe-test", label: "Test submission received", href: "/admin/form-submissions", navItemIds: ["form-submissions"] },
    ],
  },
];
