import { PRESET_STYLE_MAP } from "@/features/theme/presets/preset-style-map";

/** Preset cards shown in admin (metadata only; full theme lives in seeds/catalog/presets/*.json). */
export type PresetCatalogItem = {
  id: string;
  name: string;
  label: string;
  description: string;
  emoji: string;
  colors: string[];
  bg: string;
  cursor: string;
  text: string;
  tokens: {
    primary: string;
    accent?: string;
    secondary?: string;
    background: string;
    surface?: string;
    text?: string;
    textMuted?: string;
  };
  cardStyle?: string;
  borderStyle?: string;
  layout: { density: string; hero: string };
  blocks: string[];
};

const PRESET_CATALOG_BASE: PresetCatalogItem[] = [
  {
    id: "networking",
    name: "Networking & IPS",
    label: "Networking & IPS",
    description: "Security-first enterprise networking.",
    emoji: "🌐",
    colors: ["#00d4ff", "#00ffea", "#010409"],
    bg: "grid",
    cursor: "neon-dot",
    text: "neon-glow",
    tokens: { primary: "#00d4ff", accent: "#00ffea", background: "#010409" },
    layout: { density: "default", hero: "center" },
    blocks: ["hero", "featureGrid", "statsCounter"],
  },
  {
    id: "gaming",
    name: "Gaming & Esports",
    label: "Gaming & Esports",
    description: "High-energy neon arena styling.",
    emoji: "🎮",
    colors: ["#ff2d55", "#ff9f0a", "#0a0008"],
    bg: "particles",
    cursor: "crosshair",
    text: "glitch",
    tokens: { primary: "#ff2d55", accent: "#ff9f0a", background: "#0a0008" },
    layout: { density: "dense", hero: "left" },
    blocks: ["hero", "slider", "cta"],
  },
  {
    id: "sports",
    name: "Sports & Fitness",
    label: "Sports & Fitness",
    description: "Active gradients and bold highlights.",
    emoji: "⚽",
    colors: ["#00ff87", "#ffdd00", "#020f07"],
    bg: "waves",
    cursor: "ring-trail",
    text: "gradient-flow",
    tokens: { primary: "#00ff87", accent: "#ffdd00", background: "#020f07" },
    layout: { density: "default", hero: "center" },
    blocks: ["hero", "statsCounter", "gallery"],
  },
  {
    id: "luxury",
    name: "Luxury & Premium",
    label: "Luxury & Premium",
    description: "Elegant contrast with metallic tones.",
    emoji: "👑",
    colors: ["#c9a84c", "#f0d080", "#050400"],
    bg: "noise",
    cursor: "spotlight",
    text: "gradient-flow",
    tokens: { primary: "#c9a84c", accent: "#f0d080", background: "#050400" },
    layout: { density: "spacious", hero: "center" },
    blocks: ["hero", "gallery", "testimonials"],
  },
  {
    id: "medical",
    name: "Medical & Healthcare",
    label: "Medical & Healthcare",
    description: "Clean and calm clinical visual language.",
    emoji: "🏥",
    colors: ["#0ea5e9", "#06b6d4", "#f8fafc"],
    bg: "none",
    cursor: "neon-dot",
    text: "none",
    tokens: { primary: "#0ea5e9", accent: "#06b6d4", background: "#f8fafc" },
    layout: { density: "spacious", hero: "left" },
    blocks: ["hero", "featureGrid", "faq"],
  },
  {
    id: "agency",
    name: "Creative Agency",
    label: "Creative Agency",
    description: "Expressive gradients for brand studios.",
    emoji: "🎨",
    colors: ["#a855f7", "#ec4899", "#030014"],
    bg: "aurora",
    cursor: "magnetic",
    text: "scramble",
    tokens: { primary: "#a855f7", accent: "#ec4899", background: "#030014" },
    layout: { density: "default", hero: "left" },
    blocks: ["hero", "gallery", "cta"],
  },
  {
    id: "restaurant",
    name: "Restaurant & Food",
    label: "Restaurant & Food",
    description: "Warm colors tuned for menus and offers.",
    emoji: "🍽️",
    colors: ["#f59e0b", "#ef4444", "#0c0800"],
    bg: "bubbles",
    cursor: "spotlight",
    text: "gradient-flow",
    tokens: { primary: "#f59e0b", accent: "#ef4444", background: "#0c0800" },
    layout: { density: "default", hero: "center" },
    blocks: ["hero", "products-grid", "cta"],
  },
  {
    id: "education",
    name: "Education",
    label: "Education",
    description: "Friendly and structured learning layout.",
    emoji: "📚",
    colors: ["#6366f1", "#8b5cf6", "#f8faff"],
    bg: "geometric",
    cursor: "ring-trail",
    text: "gradient-flow",
    tokens: { primary: "#6366f1", accent: "#8b5cf6", background: "#f8faff" },
    layout: { density: "default", hero: "left" },
    blocks: ["hero", "featureGrid", "faq"],
  },
  {
    id: "realestate",
    name: "Real Estate",
    label: "Real Estate",
    description: "Premium listing visuals with muted depth.",
    emoji: "🏠",
    colors: ["#d4a853", "#e8c87a", "#0a0e15"],
    bg: "noise",
    cursor: "spotlight",
    text: "gradient-flow",
    tokens: { primary: "#d4a853", accent: "#e8c87a", background: "#0a0e15" },
    layout: { density: "spacious", hero: "center" },
    blocks: ["hero", "gallery", "cta"],
  },
  {
    id: "finance",
    name: "Finance & Banking",
    label: "Finance & Banking",
    description: "Trust-focused palette with precise accents.",
    emoji: "💰",
    colors: ["#10b981", "#34d399", "#020b07"],
    bg: "circuit",
    cursor: "crosshair",
    text: "neon-glow",
    tokens: { primary: "#10b981", accent: "#34d399", background: "#020b07" },
    layout: { density: "default", hero: "left" },
    blocks: ["hero", "statsCounter", "featureGrid"],
  },
  {
    id: "fashion",
    name: "Fashion & Lifestyle",
    label: "Fashion & Lifestyle",
    description: "Editorial contrast with vibrant highlights.",
    emoji: "👗",
    colors: ["#f43f5e", "#fb7185", "#0a0a0a"],
    bg: "noise",
    cursor: "magnetic",
    text: "scramble",
    tokens: { primary: "#f43f5e", accent: "#fb7185", background: "#0a0a0a" },
    layout: { density: "spacious", hero: "center" },
    blocks: ["hero", "gallery", "products-grid"],
  },
  {
    id: "saas",
    name: "SaaS & Software",
    label: "SaaS & Software",
    description: "Modern product-led dashboard aesthetics.",
    emoji: "💻",
    colors: ["#8b5cf6", "#a78bfa", "#05020f"],
    bg: "hexagons",
    cursor: "neon-dot",
    text: "gradient-flow",
    tokens: { primary: "#8b5cf6", accent: "#a78bfa", background: "#05020f" },
    layout: { density: "default", hero: "left" },
    blocks: ["hero", "featureGrid", "cta"],
  },
  {
    id: "automotive",
    name: "Automotive",
    label: "Automotive",
    description: "High-contrast showroom presentation.",
    emoji: "🚗",
    colors: ["#e2e8f0", "#ef4444", "#050505"],
    bg: "vortex",
    cursor: "crosshair",
    text: "glitch",
    tokens: { primary: "#e2e8f0", accent: "#ef4444", background: "#050505" },
    layout: { density: "dense", hero: "center" },
    blocks: ["hero", "gallery", "statsCounter"],
  },
  {
    id: "travel",
    name: "Travel & Tourism",
    label: "Travel & Tourism",
    description: "Bright exploration-led visual rhythm.",
    emoji: "✈️",
    colors: ["#06b6d4", "#f97316", "#020c12"],
    bg: "waves",
    cursor: "ring-trail",
    text: "typewriter",
    tokens: { primary: "#06b6d4", accent: "#f97316", background: "#020c12" },
    layout: { density: "spacious", hero: "center" },
    blocks: ["hero", "gallery", "testimonials"],
  },
  {
    id: "enterprise-wifi",
    name: "Enterprise WiFi",
    label: "Enterprise WiFi",
    description: "Reliable infrastructure-focused tone.",
    emoji: "📶",
    colors: ["#3b82f6", "#60a5fa", "#020918"],
    bg: "hexagons",
    cursor: "crosshair",
    text: "neon-glow",
    tokens: { primary: "#3b82f6", accent: "#60a5fa", background: "#020918" },
    layout: { density: "default", hero: "left" },
    blocks: ["hero", "featureGrid", "products-grid"],
  },
  {
    id: "wireless-isp",
    name: "Wireless ISP",
    label: "Wireless ISP",
    description: "Carrier-grade modern utility styling.",
    emoji: "🛰️",
    colors: ["#f97316", "#a78bfa", "#030712"],
    bg: "waves",
    cursor: "neon-dot",
    text: "gradient-flow",
    tokens: { primary: "#f97316", accent: "#a78bfa", background: "#030712" },
    layout: { density: "default", hero: "center" },
    blocks: ["hero", "statsCounter", "faq"],
  },
  {
    id: "datacenter",
    name: "Data Center",
    label: "Data Center",
    description: "Dense technical visuals for scale.",
    emoji: "🖥️",
    colors: ["#22d3ee", "#34d399", "#020617"],
    bg: "circuit",
    cursor: "crosshair",
    text: "typewriter",
    tokens: { primary: "#22d3ee", accent: "#34d399", background: "#020617" },
    layout: { density: "dense", hero: "left" },
    blocks: ["hero", "statsCounter", "featureGrid"],
  },
  {
    id: "smart-home",
    name: "Smart Home",
    label: "Smart Home",
    description: "Comfort-driven layout with warm signals.",
    emoji: "🏡",
    colors: ["#14b8a6", "#2dd4bf", "#020b0a"],
    bg: "particles",
    cursor: "ring-trail",
    text: "gradient-flow",
    tokens: { primary: "#14b8a6", accent: "#2dd4bf", background: "#020b0a" },
    layout: { density: "default", hero: "center" },
    blocks: ["hero", "featureGrid", "cta"],
  },
  {
    id: "telecom",
    name: "Telecom",
    label: "Telecom",
    description: "Network velocity and futuristic depth.",
    emoji: "📡",
    colors: ["#6366f1", "#818cf8", "#020617"],
    bg: "vortex",
    cursor: "neon-dot",
    text: "neon-glow",
    tokens: { primary: "#6366f1", accent: "#818cf8", background: "#020617" },
    layout: { density: "default", hero: "left" },
    blocks: ["hero", "products-grid", "statsCounter"],
  },
  {
    id: "brt",
    name: "BRT — Broadband Ready Technology",
    label: "BRT — Broadband",
    description: "Premium ISP / networking brand template — futuristic cyan-violet on ultra-dark.",
    emoji: "🛰️",
    colors: ["#00e5ff", "#7c3aed", "#020408"],
    bg: "circuit",
    cursor: "neon-dot",
    text: "neon-glow",
    tokens: { primary: "#00e5ff", accent: "#7c3aed", background: "#020408" },
    layout: { density: "default", hero: "center" },
    blocks: ["hero", "featureGrid", "statsCounter", "products-grid", "cta"],
  },
];

/** Catalog entries merged with Astro sample card/border styles. */
export const ALL_PRESETS: PresetCatalogItem[] = PRESET_CATALOG_BASE.map((p) => ({
  ...p,
  cardStyle: PRESET_STYLE_MAP[p.id]?.cardStyle,
  borderStyle: PRESET_STYLE_MAP[p.id]?.borderStyle,
}));

export type PresetMeta = PresetCatalogItem;
