import {
  Award,
  BarChart3,
  Building2,
  Bus,
  Car,
  CheckCircle,
  Clock,
  Compass,
  Github,
  Globe,
  Headphones,
  Heart,
  Hotel,
  Instagram,
  Linkedin,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Phone,
  Plane,
  Send,
  Share2,
  Shield,
  Star,
  TrendingUp,
  Twitter,
  Users,
  Youtube,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const MARKETING_ICON_OPTIONS = [
  { value: "shield", label: "Shield" },
  { value: "award", label: "Award" },
  { value: "star", label: "Star" },
  { value: "check", label: "Check" },
  { value: "heart", label: "Heart" },
  { value: "clock", label: "Clock" },
  { value: "headphones", label: "Headphones" },
  { value: "globe", label: "Globe" },
  { value: "lock", label: "Lock" },
  { value: "users", label: "Users" },
  { value: "trending", label: "Trending" },
  { value: "zap", label: "Zap" },
  { value: "chart", label: "Chart" },
  { value: "bus", label: "Bus" },
  { value: "car", label: "Car" },
  { value: "compass", label: "Compass" },
  { value: "hotel", label: "Hotel" },
  { value: "plane", label: "Plane" },
  { value: "phone", label: "Phone" },
  { value: "mail", label: "Mail" },
  { value: "mapPin", label: "Map pin" },
  { value: "building", label: "Building" },
  { value: "share", label: "Share" },
  { value: "send", label: "Send" },
  { value: "message", label: "Message" },
  { value: "linkedin", label: "LinkedIn" },
  { value: "twitter", label: "Twitter / X" },
  { value: "github", label: "GitHub" },
  { value: "youtube", label: "YouTube" },
  { value: "instagram", label: "Instagram" },
] as const;

const iconMap: Record<string, LucideIcon> = {
  shield: Shield,
  award: Award,
  star: Star,
  check: CheckCircle,
  heart: Heart,
  clock: Clock,
  headphones: Headphones,
  globe: Globe,
  lock: Lock,
  users: Users,
  trending: TrendingUp,
  zap: Zap,
  chart: BarChart3,
  bus: Bus,
  car: Car,
  compass: Compass,
  hotel: Hotel,
  plane: Plane,
  phone: Phone,
  mail: Mail,
  mapPin: MapPin,
  building: Building2,
  share: Share2,
  send: Send,
  message: MessageSquare,
  linkedin: Linkedin,
  twitter: Twitter,
  github: Github,
  youtube: Youtube,
  instagram: Instagram,
};

export function resolveMarketingIcon(name?: string): LucideIcon {
  if (!name) return Compass;
  return iconMap[name] ?? Compass;
}
