import { z } from "zod";
import { DEFAULT_ANNOUNCEMENT_BAR_PROPS } from "@/features/announcement-bar/announcement-bar.schema";
import { catalogPropsSchema, DEFAULT_DISPLAY_SETTINGS } from "@/schemas/catalog/display-settings";
import {
  blockAnimationSettingsSchema,
  blockLocalizationSettingsSchema,
  blockResponsiveSettingsSchema,
  blockSeoSettingsSchema,
  blockStyleSettingsSchema,
  blockVisibilityRulesSchema,
} from "@/schemas/block-system";
import { blockVisualSettingsSchema } from "@/schemas/visual-settings";

export * from "./props";

export const blockTypeSchema = z.enum([
  "hero",
  "text",
  "image",
  "gallery",
  "faq",
  "testimonials",
  "pricing",
  "cta",
  "video",
  "richText",
  "catalog",
  "contentList",
  "customHtml",
  "spacer",
  "divider",
  "section",
  "rowSection",
  "inquiryForm",
  "advancedRichText",
  "markdown",
  "code",
  "table",
  "timeline",
  "changelog",
  "comparison",
  "featureGrid",
  "benefitsGrid",
  "trustBadges",
  "announcementBar",
  "logoCloud",
  "statsCounter",
  "beforeAfter",
  "productGrid",
  "productCarousel",
  "productComparison",
  "productSpecifications",
  "productReviews",
  "productFaq",
  "relatedProducts",
  "stickyCta",
  "leadForm",
  "contactFormBuilder",
  "multiStepForm",
  "newsletterSignup",
  "downloadGate",
  "pricingCalculator",
  "knowledgeBase",
  "documentationNav",
  "statusDashboard",
  "teamDirectory",
  "partnerDirectory",
  "searchBlock",
  "advancedFilters",
  "categoryExplorer",
  "relatedContent",
  "recentlyViewed",
  "categoryShowcase",
  "brandShowcase",
  "productShowcase",
  "taxonomyProductTabs",
  "megaCollectionShowcase",
  "productDiscovery",
  "videoHero",
  "videoGallery",
  "interactiveHotspots",
  "masonryGallery",
]);

export const blockNodeSchema: z.ZodType<{
  id: string;
  type: z.infer<typeof blockTypeSchema>;
  version?: string;
  props: Record<string, unknown>;
  settings?: Record<string, unknown>;
  styles?: z.infer<typeof blockStyleSettingsSchema>;
  responsive?: z.infer<typeof blockResponsiveSettingsSchema>;
  localization?: z.infer<typeof blockLocalizationSettingsSchema>;
  visibility?: z.infer<typeof blockVisibilityRulesSchema>;
  seo?: z.infer<typeof blockSeoSettingsSchema>;
  animation?: z.infer<typeof blockAnimationSettingsSchema>;
  children?: unknown[];
}> = z.lazy(() =>
  z.object({
    id: z.string(),
    type: blockTypeSchema,
    version: z.string().optional(),
    props: z.record(z.unknown()),
    settings: z.record(z.unknown()).optional(),
    styles: blockStyleSettingsSchema.optional(),
    responsive: blockResponsiveSettingsSchema.optional(),
    localization: blockLocalizationSettingsSchema.optional(),
    visibility: blockVisibilityRulesSchema.optional(),
    seo: blockSeoSettingsSchema.optional(),
    animation: blockAnimationSettingsSchema.optional(),
    visual: blockVisualSettingsSchema.optional(),
    hidden: z.boolean().optional(),
    children: z.array(blockNodeSchema).optional(),
  })
);

export const pageBlocksSchema = z.array(blockNodeSchema);

export function createBlock(type: z.infer<typeof blockTypeSchema>, props: Record<string, unknown> = {}) {
  return {
    id: `block-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    type,
    version: "2.0" as const,
    props,
    settings: props,
    styles: {},
    responsive: {},
    visibility: {},
    seo: {},
    animation: { enabled: false },
    children: type === "section" || type === "rowSection" ? [] : undefined,
  };
}

export const BLOCK_DEFAULTS: Record<string, Record<string, unknown>> = {
  hero: {
    title: "Welcome",
    subtitle: "",
    badge: "",
    imageUrl: "",
    mediaAssetId: "",
    foregroundImageUrl: "",
    foregroundMediaAssetId: "",
    ctaLabel: "Learn more",
    ctaHref: "/contact",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    secondaryCtaVariant: "outline",
    layout: "centered",
    align: "center",
    minHeight: "70vh",
    backgroundType: "image",
    videoUrl: "",
    videoMediaAssetId: "",
    overlayOpacity: 60,
  },
  text: { content: "" },
  image: { mediaAssetId: "", url: "", alt: "" },
  gallery: {
    title: "Gallery",
    gallerySlug: "",
    variant: "grid",
    columns: 3,
    limit: 0,
    showViewAllLink: true,
  },
  faq: { title: "FAQ", faqSetSlug: "", limit: 0 },
  testimonials: {
    title: "Testimonials",
    source: "collection",
    testimonialCollectionSlug: "home",
    testimonialIds: [],
    limit: 6,
    layoutMode: "grid",
    sliderEnabled: false,
    columns: 3,
    cardVariant: "default",
    showViewAllLink: true,
    autoplay: false,
    autoplayIntervalMs: 5000,
  },
  pricing: {
    title: "Pricing",
    source: "packages",
    planSetSlug: "",
    layout: "cards",
    showBillingToggle: true,
    defaultBillingPeriod: "monthly",
    highlightedPlanId: "",
    packageCategorySlug: "",
    limit: 3,
    showFeaturedOnly: false,
  },
  cta: {
    title: "Ready to travel?",
    subtitle: "",
    button: "Contact us",
    href: "/contact",
    secondaryButton: "",
    secondaryHref: "",
    layout: "centered",
    size: "default",
    backgroundType: "gradient",
    backgroundImageUrl: "",
    backgroundMediaAssetId: "",
    backgroundColor: "",
    backgroundVideoUrl: "",
    promoBadge: "",
    promoText: "",
    countdownEnabled: false,
    countdownTarget: "",
    countdownLabel: "",
  },
  video: { title: "", url: "", caption: "" },
  richText: { html: "" },
  catalog: {
    source: "packages",
    title: "Catalog",
    subtitle: "",
    categorySlug: "",
    city: "",
    serviceType: "",
    featuredOnly: false,
    manualIds: [],
    limit: 6,
    displaySettings: DEFAULT_DISPLAY_SETTINGS,
    viewAllHref: "",
    emptyMessage: "",
  },
  contentList: {
    contentTypeSlug: "catalog-items",
    collectionSlug: "",
    title: "Featured items",
    subtitle: "",
    featuredOnly: false,
    manualIds: [],
    limit: 6,
    attributeFilters: {},
    displaySettings: DEFAULT_DISPLAY_SETTINGS,
    viewAllHref: "",
    emptyMessage: "",
  },
  customHtml: { html: "" },
  spacer: { height: 48 },
  divider: { style: "solid" },
  section: { padding: "default", background: "default" },
  rowSection: {
    padding: "default",
    background: "default",
    maxColumns: 2,
    columnLayout: "equal",
    gap: "md",
    stackOnMobile: true,
    verticalAlign: "stretch",
  },
  inquiryForm: {
    title: "Send an Inquiry",
    type: "CONTACT",
  },
  advancedRichText: {
    content: "",
    html: "<p>Enter your content here...</p>",
    maxWidth: "reading",
    prose: true,
  },
  markdown: {
    markdown: "# Hello\n\nWrite **markdown** here.",
    prose: true,
    allowGfm: true,
  },
  code: {
    code: 'console.log("Hello, world!");',
    language: "typescript",
    title: "",
    showLineNumbers: true,
    showCopyButton: true,
    highlightLines: [],
  },
  table: {
    title: "Data Table",
    columns: [],
    rows: [],
    features: {
      sortable: true,
      filterable: false,
      searchable: true,
      paginated: false,
      pageSize: 10,
    },
    striped: true,
    compact: false,
  },
  timeline: {
    title: "Timeline",
    layout: "vertical",
    items: [],
  },
  changelog: {
    title: "Release Notes",
    releaseSetSlug: "",
    layout: "timeline",
    filterTags: [],
    filterStatuses: [],
    releases: [],
  },
  comparison: {
    title: "Compare plans",
    source: "manual",
    layout: "table",
    highlightDifferences: true,
    columns: [],
    rows: [],
    contentTypeSlug: "",
    itemIds: [],
    catalogSource: "packages",
    attributeKeys: [],
  },
  featureGrid: {
    title: "Features",
    subtitle: "",
    columns: 3,
    cardVariant: "default",
    showCategories: false,
    items: [],
  },
  benefitsGrid: {
    title: "Why choose us",
    subtitle: "",
    layout: "cards",
    emphasis: "outcome",
    items: [],
  },
  trustBadges: {
    title: "Trusted & certified",
    subtitle: "",
    layout: "grid",
    registrationNo: "",
    items: [],
  },
  announcementBar: DEFAULT_ANNOUNCEMENT_BAR_PROPS,
  logoCloud: {
    title: "Our partners",
    subtitle: "",
    displayMode: "grid",
    columns: 5,
    grayscale: true,
    grayscaleHover: true,
    autoplay: true,
    autoplayIntervalMs: 4000,
    logoSize: "md",
    groupByCategory: false,
    items: [],
  },
  statsCounter: {
    title: "By the numbers",
    subtitle: "",
    layout: "grid",
    animateOnView: true,
    items: [],
  },
  beforeAfter: {
    title: "See the difference",
    subtitle: "",
    layout: "slider",
    beforeLabel: "Before",
    afterLabel: "After",
    beforeImageUrl: "",
    beforeMediaAssetId: "",
    afterImageUrl: "",
    afterMediaAssetId: "",
    sliderPosition: 50,
    showLabels: true,
  },
  productGrid: {
    title: "Products",
    subtitle: "",
    badge: "",
    source: "collection",
    collectionSlug: "",
    productSlugs: [],
    tags: [],
    limit: 8,
    sortBy: "name-asc",
    columns: 3,
    viewMode: "grid",
    showToolbar: false,
    pageSize: 12,
    showPrice: true,
    showRating: true,
    showStock: true,
    showCompare: true,
    emptyMessage: "",
    viewAllHref: "",
  },
  productCarousel: {
    title: "Featured products",
    subtitle: "",
    source: "collection",
    collectionSlug: "",
    productSlugs: [],
    tags: [],
    limit: 8,
    sortBy: "name-asc",
    cardVariant: "default",
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
    emptyMessage: "",
  },
  productComparison: {
    title: "Compare products",
    productSlugs: [],
    layout: "table",
    highlightDifferences: true,
    compareMode: "all",
    showCompareLink: true,
  },
  productSpecifications: {
    title: "Specifications",
    productSlug: "",
    expandFirstGroup: true,
    manualGroups: [],
  },
  productReviews: {
    title: "Customer reviews",
    productSlug: "",
    commentsLimit: 10,
    allowSorting: true,
    showTrustpilotBanner: true,
  },
  productFaq: {
    title: "Product FAQ",
    source: "manual",
    productSlug: "",
    items: [],
    searchable: false,
    layoutMode: "accordion",
  },
  relatedProducts: {
    title: "You may also like",
    rule: "collection",
    anchorSlug: "",
    collectionSlug: "",
    brand: "",
    tags: [],
    productSlugs: [],
    limit: 4,
    layout: "grid",
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
  },
  stickyCta: {
    title: "",
    message: "Ready to get started?",
    primaryButton: "Contact us",
    primaryHref: "/contact",
    secondaryButton: "",
    secondaryHref: "",
    variant: "bar",
    position: "bottom",
    trigger: "scrollPercent",
    triggerValue: 25,
    dismissible: true,
    dismissKey: "sticky-cta",
  },
  leadForm: {
    title: "Get in touch",
    subtitle: "",
    templateId: "",
    incentive: "",
    successMessage: "Thank you! We will be in touch.",
  },
  contactFormBuilder: {
    title: "Contact us",
    templateId: "",
    layout: "stacked",
    successMessage: "Message sent successfully.",
    redirectUrl: "",
  },
  multiStepForm: {
    title: "Application",
    templateId: "",
    progressStyle: "bar",
    allowBack: true,
    saveAndResume: true,
    successMessage: "Submission complete.",
  },
  newsletterSignup: {
    title: "Subscribe to our newsletter",
    subtitle: "",
    layout: "inline",
    segment: "default",
    incentive: "",
    doubleOptIn: true,
    showNameField: false,
    successMessage: "You're subscribed!",
    pendingMessage: "Check your email to confirm.",
    webhookUrl: "",
  },
  searchBlock: {
    title: "Search",
    subtitle: "",
    layout: "inline",
    resultsMode: "dropdown",
    placeholder: "",
    showPopular: true,
    showTrending: true,
    showRecentQueries: true,
    showEntityTypeChips: true,
    showFacetChips: true,
    entityTypes: [],
    redirectPath: "/search",
  },
  advancedFilters: {
    title: "",
    subtitle: "",
    scope: "products",
    layout: "sidebar",
    syncUrl: true,
    enabledDimensions: [],
    contentTypeSlug: "",
    pairedBlockId: "",
  },
  categoryExplorer: {
    title: "Browse",
    subtitle: "",
    source: "collections",
    variant: "tabs",
    contentTypeSlug: "",
    featuredSlugs: [],
    showImages: true,
    showCounts: false,
    maxDepth: 3,
    pageSize: 12,
    enablePagination: true,
    manualNodes: [],
    urlParamKey: "",
  },
  relatedContent: {
    title: "Related",
    subtitle: "",
    entityTypes: ["CATALOG_PRODUCT", "POST", "CONTENT_ITEM"],
    rule: "taxonomy",
    anchorContext: "page",
    anchorSlug: "",
    anchorId: "",
    categorySlugs: [],
    tags: [],
    collectionSlug: "",
    contentTypeSlug: "",
    manualItems: [],
    limit: 6,
    layout: "grid",
    columns: 3,
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
  },
  recentlyViewed: {
    title: "Recently viewed",
    subtitle: "",
    entityTypes: [],
    limit: 8,
    layout: "grid",
    columns: 4,
    excludeCurrentPage: true,
    emptyMessage: "",
  },
  categoryShowcase: {
    title: "Shop by category",
    subtitle: "",
    badge: "",
    source: "collections",
    layout: "grid",
    selection: "auto",
    manualSlugs: [],
    featuredSlugs: [],
    manualNodes: [],
    showImages: true,
    showCounts: true,
    showDescriptions: false,
    columns: 4,
    maxDepth: 3,
    limit: 12,
    sort: "name",
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 4,
  },
  brandShowcase: {
    title: "Our brands",
    subtitle: "",
    badge: "",
    source: "catalogProfiles",
    brandSelection: "all",
    layout: "logoCarousel",
    sort: "featuredFirst",
    manualBrands: [],
    featuredSlugs: [],
    selectedBrandSlugs: [],
    manualSlugs: [],
    brandOverrides: {},
    showCounts: true,
    showDescriptions: false,
    grayscale: true,
    grayscaleHover: true,
    searchEnabled: false,
    limit: 12,
    columns: 4,
    logoCarouselMode: "carousel",
    logoSize: "md",
    scrollSpeed: "medium",
    scrollDirection: "left",
    pauseOnHover: true,
    showEdgeFade: true,
    separator: "",
    autoplay: true,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 4,
  },
  productShowcase: {
    title: "Featured products",
    subtitle: "",
    badge: "",
    mode: "single",
    layout: "carousel",
    source: "featured",
    collectionSlug: "",
    productSlugs: [],
    tags: [],
    brand: "",
    category: "",
    limit: 8,
    sortBy: "name-asc",
    columns: 3,
    tabs: [],
    cardVariant: "default",
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
    showPrice: true,
    showRating: true,
    showStock: true,
    showCompare: true,
    viewAllHref: "",
    emptyMessage: "",
    anchorSlug: "",
  },
  taxonomyProductTabs: {
    title: "Browse collections",
    subtitle: "",
    badge: "",
    taxonomy: "category",
    navStyle: "pills",
    tabSource: "auto",
    autoTabLimit: 6,
    selectedBrandSlugs: [],
    brandOverrides: {},
    tabs: [],
    productLayout: "grid",
    productsPerTab: 8,
    sortBy: "name-asc",
    columns: 3,
    lazyLoad: true,
    showTabCounts: true,
    ajaxEnabled: true,
    cardVariant: "default",
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
    showPrice: true,
    showRating: true,
    showStock: true,
    showCompare: true,
    emptyMessage: "",
  },
  megaCollectionShowcase: {
    title: "Mega collection",
    subtitle: "",
    badge: "",
    leftNavSource: "collections",
    leftNavMaxDepth: 3,
    leftShowIcons: true,
    centerCollectionSlug: "",
    centerCategory: "",
    centerLayout: "grid",
    centerLimit: 8,
    centerSortBy: "name-asc",
    centerColumns: 3,
    syncNavToProducts: true,
    rightPromoImageUrl: "",
    rightPromoTitle: "",
    rightPromoCta: "",
    rightPromoHref: "",
    rightFeaturedBrandSlug: "",
    showPrice: true,
    showRating: true,
    showStock: true,
    showCompare: true,
  },
  productDiscovery: {
    title: "Discover products",
    subtitle: "",
    badge: "",
    layout: "grid",
    loadMode: "paginated",
    ajaxEnabled: true,
    syncUrl: false,
    showResultCount: true,
    pageSize: 12,
    columns: 3,
    enabledDimensions: ["categories", "brands", "tags", "price", "availability"],
    collectionSlug: "",
    personalizationRecentlyViewedBoost: false,
    personalizationTrendingBoost: false,
    showPrice: true,
    showRating: true,
    showStock: true,
    showCompare: true,
    emptyMessage: "",
  },
  videoHero: {
    title: "Experience in motion",
    subtitle: "",
    badge: "",
    ctaLabel: "Get started",
    ctaHref: "/contact",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    secondaryCtaVariant: "outline",
    mediaMode: "single",
    videoUrl: "",
    videoMediaAssetId: "",
    posterUrl: "",
    captionTrackUrl: "",
    slides: [],
    layout: "fullBleed",
    align: "center",
    minHeight: "70vh",
    autoplay: true,
    loop: true,
    muted: true,
    showControls: false,
    playsInline: true,
    overlayOpacity: 55,
    overlayGradient: true,
    autoplaySlides: true,
    autoplaySlideMs: 6000,
    showSlideDots: true,
    showSlideArrows: true,
  },
  videoGallery: {
    title: "Video gallery",
    subtitle: "",
    source: "inline",
    gallerySlug: "",
    items: [],
    columns: 3,
    layout: "grid",
    limit: 0,
    enableLightbox: true,
    autoplayInGrid: false,
    showCategories: false,
    showControls: true,
    loop: false,
    preload: "metadata",
  },
  interactiveHotspots: {
    title: "Explore",
    subtitle: "",
    imageUrl: "",
    mediaAssetId: "",
    interaction: "click",
    panelStyle: "popover",
    hotspots: [],
  },
  masonryGallery: {
    title: "Gallery",
    subtitle: "",
    source: "inline",
    gallerySlug: "",
    items: [],
    columns: 3,
    limit: 0,
    enableLightbox: true,
    enableFilter: false,
    lazyLoad: true,
  },
  downloadGate: {
    title: "Download resource",
    description: "Complete the form to access this file.",
    mediaAssetId: "",
    fileLabel: "Download",
    successMessage: "Download unlocked.",
    unlockMethod: "formTemplate",
    templateId: "",
    newsletterSegment: "default",
    externalUrl: "",
    expiryHours: 72,
  },
  pricingCalculator: {
    title: "Pricing Calculator",
    subtitle: "",
    pricingCalculatorSlug: "",
    showDescription: true,
    layout: "stacked",
  },
  knowledgeBase: {
    title: "Knowledge Base",
    subtitle: "",
    knowledgeBaseSlug: "",
    layout: "grid",
    showSearch: true,
    showCategories: true,
    categorySlug: "",
    limit: 0,
    showRatings: true,
  },
  documentationNav: {
    title: "Documentation",
    subtitle: "",
    docPortalSlug: "",
    versionSlug: "",
    layout: "sidebar",
    showBreadcrumbs: true,
    showSearch: true,
    showToc: true,
    rootSectionSlug: "",
  },
  statusDashboard: {
    title: "System Status",
    subtitle: "",
    statusBoardSlug: "",
    layout: "full",
    showUptime: true,
    showIncidents: true,
    showMaintenance: true,
    pollingIntervalMs: 60000,
  },
  teamDirectory: {
    title: "Our Team",
    subtitle: "",
    teamDirectorySlug: "",
    layout: "grid",
    showSearch: true,
    showDepartments: true,
    departmentId: "",
    limit: 0,
  },
  partnerDirectory: {
    title: "Partners",
    subtitle: "",
    partnerProgramSlug: "",
    layout: "grid",
    showSearch: true,
    categorySlug: "",
    locationFilter: "",
    limit: 0,
    showMap: false,
  },
};

/** Keys whose string values are editor placeholder text — blank on load. */
const BLANKABLE_DEFAULT_KEYS = new Set([
  "title",
  "subtitle",
  "content",
  "body",
  "html",
  "markdown",
  "description",
  "message",
  "incentive",
  "caption",
  "alt",
  "emptyMessage",
  "badge",
  "ctaLabel",
  "secondaryCtaLabel",
  "button",
  "secondaryButton",
  "promoBadge",
  "promoText",
  "countdownLabel",
  "beforeLabel",
  "afterLabel",
  "label",
  "name",
  "placeholder",
  "excerpt",
  "primaryButton",
]);

function shouldBlankDefaultString(key: string): boolean {
  if (key.endsWith("En") || key.endsWith("Ar")) return true;
  return BLANKABLE_DEFAULT_KEYS.has(key);
}

function blankDefaultStrings<T>(value: T, key?: string): T {
  if (typeof value === "string") {
    return key && shouldBlankDefaultString(key) ? ("" as T) : value;
  }
  if (Array.isArray(value)) {
    return value.map((entry) => blankDefaultStrings(entry)) as T;
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([entryKey, entry]) => [
        entryKey,
        blankDefaultStrings(entry, entryKey),
      ])
    ) as T;
  }
  return value;
}

for (const key of Object.keys(BLOCK_DEFAULTS)) {
  BLOCK_DEFAULTS[key] = blankDefaultStrings(BLOCK_DEFAULTS[key]) as Record<string, unknown>;
}
