import { z } from "zod";
import { DEFAULT_ANNOUNCEMENT_BAR_PROPS } from "@/features/announcement-bar/announcement-bar.schema";
import { catalogPropsSchema, DEFAULT_DISPLAY_SETTINGS } from "@/schemas/catalog/display-settings";
import {
  blockAnimationSettingsSchema,
  blockLocalizationSettingsSchema,
  blockResponsiveSettingsSchema,
  blockSeoSettingsSchema,
  blockStyleSettingsSchema,
  blockVisibilityRulesSchema,
} from "@/schemas/block-system";
import { blockVisualSettingsSchema } from "@/schemas/visual-settings";

export * from "./props";

export const blockTypeSchema = z.enum([
  "hero",
  "text",
  "image",
  "gallery",
  "faq",
  "testimonials",
  "pricing",
  "cta",
  "video",
  "richText",
  "catalog",
  "contentList",
  "customHtml",
  "spacer",
  "divider",
  "section",
  "rowSection",
  "inquiryForm",
  "advancedRichText",
  "markdown",
  "code",
  "table",
  "timeline",
  "changelog",
  "comparison",
  "featureGrid",
  "benefitsGrid",
  "trustBadges",
  "announcementBar",
  "logoCloud",
  "statsCounter",
  "beforeAfter",
  "productGrid",
  "productCarousel",
  "productComparison",
  "productSpecifications",
  "productReviews",
  "productFaq",
  "relatedProducts",
  "stickyCta",
  "leadForm",
  "contactFormBuilder",
  "multiStepForm",
  "newsletterSignup",
  "downloadGate",
  "pricingCalculator",
  "knowledgeBase",
  "documentationNav",
  "statusDashboard",
  "teamDirectory",
  "partnerDirectory",
  "searchBlock",
  "advancedFilters",
  "categoryExplorer",
  "relatedContent",
  "recentlyViewed",
  "videoHero",
  "videoGallery",
  "interactiveHotspots",
  "masonryGallery",
]);

export const blockNodeSchema: z.ZodType<{
  id: string;
  type: z.infer<typeof blockTypeSchema>;
  version?: string;
  props: Record<string, unknown>;
  settings?: Record<string, unknown>;
  styles?: z.infer<typeof blockStyleSettingsSchema>;
  responsive?: z.infer<typeof blockResponsiveSettingsSchema>;
  localization?: z.infer<typeof blockLocalizationSettingsSchema>;
  visibility?: z.infer<typeof blockVisibilityRulesSchema>;
  seo?: z.infer<typeof blockSeoSettingsSchema>;
  animation?: z.infer<typeof blockAnimationSettingsSchema>;
  children?: unknown[];
}> = z.lazy(() =>
  z.object({
    id: z.string(),
    type: blockTypeSchema,
    version: z.string().optional(),
    props: z.record(z.unknown()),
    settings: z.record(z.unknown()).optional(),
    styles: blockStyleSettingsSchema.optional(),
    responsive: blockResponsiveSettingsSchema.optional(),
    localization: blockLocalizationSettingsSchema.optional(),
    visibility: blockVisibilityRulesSchema.optional(),
    seo: blockSeoSettingsSchema.optional(),
    animation: blockAnimationSettingsSchema.optional(),
    visual: blockVisualSettingsSchema.optional(),
    hidden: z.boolean().optional(),
    children: z.array(blockNodeSchema).optional(),
  })
);

export const pageBlocksSchema = z.array(blockNodeSchema);

export function createBlock(type: z.infer<typeof blockTypeSchema>, props: Record<string, unknown> = {}) {
  return {
    id: `block-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    type,
    version: "2.0" as const,
    props,
    settings: props,
    styles: {},
    responsive: {},
    visibility: {},
    seo: {},
    animation: { enabled: false },
    children: type === "section" || type === "rowSection" ? [] : undefined,
  };
}

export const BLOCK_DEFAULTS: Record<string, Record<string, unknown>> = {
  hero: {
    titleEn: "Welcome",
    titleAr: "مرحباً",
    subtitleEn: "",
    subtitleAr: "",
    badgeEn: "",
    badgeAr: "",
    imageUrl: "",
    mediaAssetId: "",
    foregroundImageUrl: "",
    foregroundMediaAssetId: "",
    ctaLabelEn: "Learn more",
    ctaLabelAr: "اعرف المزيد",
    ctaHref: "/contact",
    secondaryCtaLabelEn: "",
    secondaryCtaLabelAr: "",
    secondaryCtaHref: "",
    secondaryCtaVariant: "outline",
    layout: "centered",
    align: "center",
    minHeight: "70vh",
    backgroundType: "image",
    videoUrl: "",
    videoMediaAssetId: "",
    overlayOpacity: 60,
  },
  text: { contentEn: "", contentAr: "" },
  image: { mediaAssetId: "", url: "", altEn: "", altAr: "" },
  gallery: {
    titleEn: "Gallery",
    titleAr: "المعرض",
    gallerySlug: "",
    columns: 3,
    limit: 0,
    showViewAllLink: true,
  },
  faq: { titleEn: "FAQ", titleAr: "الأسئلة الشائعة", faqSetSlug: "", limit: 0 },
  testimonials: {
    titleEn: "Testimonials",
    titleAr: "آراء العملاء",
    source: "collection",
    testimonialCollectionSlug: "home",
    testimonialIds: [],
    limit: 6,
    layoutMode: "grid",
    sliderEnabled: false,
    columns: 3,
    cardVariant: "default",
    showViewAllLink: true,
    autoplay: false,
    autoplayIntervalMs: 5000,
  },
  pricing: {
    titleEn: "Pricing",
    titleAr: "الأسعار",
    source: "packages",
    planSetSlug: "",
    layout: "cards",
    showBillingToggle: true,
    defaultBillingPeriod: "monthly",
    highlightedPlanId: "",
    packageCategorySlug: "",
    limit: 3,
    showFeaturedOnly: false,
  },
  cta: {
    titleEn: "Ready to travel?",
    titleAr: "هل أنت مستعد للسفر؟",
    subtitleEn: "",
    subtitleAr: "",
    buttonEn: "Contact us",
    buttonAr: "تواصل معنا",
    href: "/contact",
    secondaryButtonEn: "",
    secondaryButtonAr: "",
    secondaryHref: "",
    layout: "centered",
    size: "default",
    backgroundType: "gradient",
    backgroundImageUrl: "",
    backgroundMediaAssetId: "",
    backgroundColor: "",
    backgroundVideoUrl: "",
    promoBadgeEn: "",
    promoBadgeAr: "",
    promoTextEn: "",
    promoTextAr: "",
    countdownEnabled: false,
    countdownTarget: "",
    countdownLabelEn: "",
    countdownLabelAr: "",
  },
  video: { titleEn: "", titleAr: "", url: "", captionEn: "", captionAr: "" },
  richText: { htmlEn: "", htmlAr: "" },
  catalog: {
    source: "packages",
    titleEn: "Catalog",
    titleAr: "العروض",
    subtitleEn: "",
    subtitleAr: "",
    categorySlug: "",
    city: "",
    serviceType: "",
    featuredOnly: false,
    manualIds: [],
    limit: 6,
    displaySettings: DEFAULT_DISPLAY_SETTINGS,
    viewAllHref: "",
    emptyMessageEn: "",
    emptyMessageAr: "",
  },
  contentList: {
    contentTypeSlug: "catalog-items",
    collectionSlug: "",
    titleEn: "Featured items",
    titleAr: "عناصر مميزة",
    subtitleEn: "",
    subtitleAr: "",
    featuredOnly: false,
    manualIds: [],
    limit: 6,
    attributeFilters: {},
    displaySettings: DEFAULT_DISPLAY_SETTINGS,
    viewAllHref: "",
    emptyMessageEn: "",
    emptyMessageAr: "",
  },
  customHtml: { htmlEn: "", htmlAr: "" },
  spacer: { height: 48 },
  divider: { style: "solid" },
  section: { padding: "default", background: "default" },
  rowSection: {
    padding: "default",
    background: "default",
    maxColumns: 2,
    columnLayout: "equal",
    gap: "md",
    stackOnMobile: true,
    verticalAlign: "stretch",
  },
  inquiryForm: {
    titleEn: "Send an Inquiry",
    titleAr: "أرسل استفساراً",
    type: "CONTACT",
  },
  advancedRichText: {
    contentEn: "",
    contentAr: "",
    htmlEn: "<p>Enter your content here...</p>",
    htmlAr: "",
    maxWidth: "reading",
    prose: true,
  },
  markdown: {
    markdownEn: "# Hello\n\nWrite **markdown** here.",
    markdownAr: "",
    prose: true,
    allowGfm: true,
  },
  code: {
    code: 'console.log("Hello, world!");',
    language: "typescript",
    titleEn: "",
    titleAr: "",
    showLineNumbers: true,
    showCopyButton: true,
    highlightLines: [],
  },
  table: {
    titleEn: "Data Table",
    titleAr: "",
    columns: [],
    rows: [],
    features: {
      sortable: true,
      filterable: false,
      searchable: true,
      paginated: false,
      pageSize: 10,
    },
    striped: true,
    compact: false,
  },
  timeline: {
    titleEn: "Timeline",
    titleAr: "الجدول الزمني",
    layout: "vertical",
    items: [],
  },
  changelog: {
    titleEn: "Release Notes",
    titleAr: "ملاحظات الإصدار",
    releaseSetSlug: "",
    layout: "timeline",
    filterTags: [],
    filterStatuses: [],
    releases: [],
  },
  comparison: {
    titleEn: "Compare plans",
    titleAr: "قارن الخطط",
    source: "manual",
    layout: "table",
    highlightDifferences: true,
    columns: [],
    rows: [],
    contentTypeSlug: "",
    itemIds: [],
    catalogSource: "packages",
    attributeKeys: [],
  },
  featureGrid: {
    titleEn: "Features",
    titleAr: "المميزات",
    subtitleEn: "",
    subtitleAr: "",
    columns: 3,
    cardVariant: "default",
    showCategories: false,
    items: [],
  },
  benefitsGrid: {
    titleEn: "Why choose us",
    titleAr: "لماذا نحن",
    subtitleEn: "",
    subtitleAr: "",
    layout: "cards",
    emphasis: "outcome",
    items: [],
  },
  trustBadges: {
    titleEn: "Trusted & certified",
    titleAr: "موثوق ومعتمد",
    subtitleEn: "",
    subtitleAr: "",
    layout: "grid",
    registrationNo: "",
    items: [],
  },
  announcementBar: DEFAULT_ANNOUNCEMENT_BAR_PROPS,
  logoCloud: {
    titleEn: "Our partners",
    titleAr: "شركاؤنا",
    subtitleEn: "",
    subtitleAr: "",
    displayMode: "grid",
    columns: 5,
    grayscale: true,
    grayscaleHover: true,
    autoplay: true,
    autoplayIntervalMs: 4000,
    logoSize: "md",
    groupByCategory: false,
    items: [],
  },
  statsCounter: {
    titleEn: "By the numbers",
    titleAr: "بالأرقام",
    subtitleEn: "",
    subtitleAr: "",
    layout: "grid",
    animateOnView: true,
    items: [],
  },
  beforeAfter: {
    titleEn: "See the difference",
    titleAr: "شاهد الفرق",
    subtitleEn: "",
    subtitleAr: "",
    layout: "slider",
    beforeLabelEn: "Before",
    beforeLabelAr: "قبل",
    afterLabelEn: "After",
    afterLabelAr: "بعد",
    beforeImageUrl: "",
    beforeMediaAssetId: "",
    afterImageUrl: "",
    afterMediaAssetId: "",
    sliderPosition: 50,
    showLabels: true,
  },
  productGrid: {
    titleEn: "Products",
    titleAr: "المنتجات",
    subtitleEn: "",
    subtitleAr: "",
    badgeEn: "",
    badgeAr: "",
    source: "collection",
    collectionSlug: "",
    productSlugs: [],
    tags: [],
    limit: 8,
    sortBy: "name-asc",
    columns: 3,
    viewMode: "grid",
    showToolbar: false,
    pageSize: 12,
    showPrice: true,
    showRating: true,
    showStock: true,
    showCompare: true,
    emptyMessageEn: "",
    emptyMessageAr: "",
    viewAllHref: "",
  },
  productCarousel: {
    titleEn: "Featured products",
    titleAr: "منتجات مميزة",
    subtitleEn: "",
    subtitleAr: "",
    source: "collection",
    collectionSlug: "",
    productSlugs: [],
    tags: [],
    limit: 8,
    sortBy: "name-asc",
    cardVariant: "default",
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
    emptyMessageEn: "",
    emptyMessageAr: "",
  },
  productComparison: {
    titleEn: "Compare products",
    titleAr: "قارن المنتجات",
    productSlugs: [],
    layout: "table",
    highlightDifferences: true,
    compareMode: "all",
    showCompareLink: true,
  },
  productSpecifications: {
    titleEn: "Specifications",
    titleAr: "المواصفات",
    productSlug: "",
    expandFirstGroup: true,
    manualGroups: [],
  },
  productReviews: {
    titleEn: "Customer reviews",
    titleAr: "آراء العملاء",
    productSlug: "",
    commentsLimit: 10,
    allowSorting: true,
    showTrustpilotBanner: true,
  },
  productFaq: {
    titleEn: "Product FAQ",
    titleAr: "أسئلة المنتج",
    source: "manual",
    productSlug: "",
    items: [],
    searchable: false,
    layoutMode: "accordion",
  },
  relatedProducts: {
    titleEn: "You may also like",
    titleAr: "قد يعجبك أيضاً",
    rule: "collection",
    anchorSlug: "",
    collectionSlug: "",
    brand: "",
    tags: [],
    productSlugs: [],
    limit: 4,
    layout: "grid",
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
  },
  stickyCta: {
    titleEn: "",
    titleAr: "",
    messageEn: "Ready to get started?",
    messageAr: "هل أنت مستعد للبدء؟",
    primaryButtonEn: "Contact us",
    primaryButtonAr: "تواصل معنا",
    primaryHref: "/contact",
    secondaryButtonEn: "",
    secondaryButtonAr: "",
    secondaryHref: "",
    variant: "bar",
    position: "bottom",
    trigger: "scrollPercent",
    triggerValue: 25,
    dismissible: true,
    dismissKey: "sticky-cta",
  },
  leadForm: {
    titleEn: "Get in touch",
    titleAr: "تواصل معنا",
    subtitleEn: "",
    subtitleAr: "",
    templateId: "",
    incentiveEn: "",
    incentiveAr: "",
    successMessageEn: "Thank you! We will be in touch.",
    successMessageAr: "شكراً! سنتواصل معك قريباً.",
  },
  contactFormBuilder: {
    titleEn: "Contact us",
    titleAr: "اتصل بنا",
    templateId: "",
    layout: "stacked",
    successMessageEn: "Message sent successfully.",
    successMessageAr: "تم إرسال رسالتك بنجاح.",
    redirectUrl: "",
  },
  multiStepForm: {
    titleEn: "Application",
    titleAr: "الطلب",
    templateId: "",
    progressStyle: "bar",
    allowBack: true,
    saveAndResume: true,
    successMessageEn: "Submission complete.",
    successMessageAr: "تم الإرسال بنجاح.",
  },
  newsletterSignup: {
    titleEn: "Subscribe to our newsletter",
    titleAr: "اشترك في نشرتنا",
    subtitleEn: "",
    subtitleAr: "",
    layout: "inline",
    segment: "default",
    incentiveEn: "",
    incentiveAr: "",
    doubleOptIn: true,
    showNameField: false,
    successMessageEn: "You're subscribed!",
    successMessageAr: "تم الاشتراك!",
    pendingMessageEn: "Check your email to confirm.",
    pendingMessageAr: "تحقق من بريدك لتأكيد الاشتراك.",
    webhookUrl: "",
  },
  searchBlock: {
    titleEn: "Search",
    titleAr: "بحث",
    subtitleEn: "",
    subtitleAr: "",
    layout: "inline",
    resultsMode: "dropdown",
    placeholderEn: "",
    placeholderAr: "",
    showPopular: true,
    showTrending: true,
    showRecentQueries: true,
    showEntityTypeChips: true,
    showFacetChips: true,
    entityTypes: [],
    redirectPath: "/search",
  },
  advancedFilters: {
    titleEn: "",
    titleAr: "",
    subtitleEn: "",
    subtitleAr: "",
    scope: "products",
    layout: "sidebar",
    syncUrl: true,
    enabledDimensions: [],
    contentTypeSlug: "",
    pairedBlockId: "",
  },
  categoryExplorer: {
    titleEn: "Browse",
    titleAr: "تصفح",
    subtitleEn: "",
    subtitleAr: "",
    source: "collections",
    variant: "tabs",
    contentTypeSlug: "",
    featuredSlugs: [],
    showImages: true,
    showCounts: false,
    maxDepth: 3,
    pageSize: 12,
    enablePagination: true,
    manualNodes: [],
    urlParamKey: "",
  },
  relatedContent: {
    titleEn: "Related",
    titleAr: "ذات صلة",
    subtitleEn: "",
    subtitleAr: "",
    entityTypes: ["CATALOG_PRODUCT", "POST", "CONTENT_ITEM"],
    rule: "taxonomy",
    anchorContext: "page",
    anchorSlug: "",
    anchorId: "",
    categorySlugs: [],
    tags: [],
    collectionSlug: "",
    contentTypeSlug: "",
    manualItems: [],
    limit: 6,
    layout: "grid",
    columns: 3,
    autoplay: false,
    autoplayIntervalMs: 5000,
    showArrows: true,
    showDots: false,
    loop: true,
    slidesPerView: 3,
  },
  recentlyViewed: {
    titleEn: "Recently viewed",
    titleAr: "شوهد مؤخراً",
    subtitleEn: "",
    subtitleAr: "",
    entityTypes: [],
    limit: 8,
    layout: "grid",
    columns: 4,
    excludeCurrentPage: true,
    emptyMessageEn: "",
    emptyMessageAr: "",
  },
  videoHero: {
    titleEn: "Experience in motion",
    titleAr: "تجربة متحركة",
    subtitleEn: "",
    subtitleAr: "",
    badgeEn: "",
    badgeAr: "",
    ctaLabelEn: "Get started",
    ctaLabelAr: "ابدأ",
    ctaHref: "/contact",
    secondaryCtaLabelEn: "",
    secondaryCtaLabelAr: "",
    secondaryCtaHref: "",
    secondaryCtaVariant: "outline",
    mediaMode: "single",
    videoUrl: "",
    videoMediaAssetId: "",
    posterUrl: "",
    captionTrackUrl: "",
    slides: [],
    layout: "fullBleed",
    align: "center",
    minHeight: "70vh",
    autoplay: true,
    loop: true,
    muted: true,
    showControls: false,
    playsInline: true,
    overlayOpacity: 55,
    overlayGradient: true,
    autoplaySlides: true,
    autoplaySlideMs: 6000,
    showSlideDots: true,
    showSlideArrows: true,
  },
  videoGallery: {
    titleEn: "Video gallery",
    titleAr: "معرض الفيديو",
    subtitleEn: "",
    subtitleAr: "",
    source: "inline",
    gallerySlug: "",
    items: [],
    columns: 3,
    layout: "grid",
    limit: 0,
    enableLightbox: true,
    autoplayInGrid: false,
    showCategories: false,
    showControls: true,
    loop: false,
    preload: "metadata",
  },
  interactiveHotspots: {
    titleEn: "Explore",
    titleAr: "استكشف",
    subtitleEn: "",
    subtitleAr: "",
    imageUrl: "",
    mediaAssetId: "",
    interaction: "click",
    panelStyle: "popover",
    hotspots: [],
  },
  masonryGallery: {
    titleEn: "Gallery",
    titleAr: "المعرض",
    subtitleEn: "",
    subtitleAr: "",
    source: "inline",
    gallerySlug: "",
    items: [],
    columns: 3,
    limit: 0,
    enableLightbox: true,
    enableFilter: false,
    lazyLoad: true,
  },
  downloadGate: {
    titleEn: "Download resource",
    titleAr: "تحميل المورد",
    descriptionEn: "Complete the form to access this file.",
    descriptionAr: "أكمل النموذج للوصول إلى هذا الملف.",
    mediaAssetId: "",
    fileLabelEn: "Download",
    fileLabelAr: "تحميل",
    unlockMethod: "formTemplate",
    templateId: "",
    newsletterSegment: "default",
    externalUrl: "",
    expiryHours: 72,
  },
  pricingCalculator: {
    titleEn: "Pricing Calculator",
    titleAr: "حاسبة الأسعار",
    subtitleEn: "",
    subtitleAr: "",
    pricingCalculatorSlug: "",
    showDescription: true,
    layout: "stacked",
  },
  knowledgeBase: {
    titleEn: "Knowledge Base",
    titleAr: "قاعدة المعرفة",
    subtitleEn: "",
    subtitleAr: "",
    knowledgeBaseSlug: "",
    layout: "grid",
    showSearch: true,
    showCategories: true,
    categorySlug: "",
    limit: 0,
    showRatings: true,
  },
  documentationNav: {
    titleEn: "Documentation",
    titleAr: "التوثيق",
    subtitleEn: "",
    subtitleAr: "",
    docPortalSlug: "",
    versionSlug: "",
    layout: "sidebar",
    showBreadcrumbs: true,
    showSearch: true,
    showToc: true,
    rootSectionSlug: "",
  },
  statusDashboard: {
    titleEn: "System Status",
    titleAr: "حالة النظام",
    subtitleEn: "",
    subtitleAr: "",
    statusBoardSlug: "",
    layout: "full",
    showUptime: true,
    showIncidents: true,
    showMaintenance: true,
    pollingIntervalMs: 60000,
  },
  teamDirectory: {
    titleEn: "Our Team",
    titleAr: "فريقنا",
    subtitleEn: "",
    subtitleAr: "",
    teamDirectorySlug: "",
    layout: "grid",
    showSearch: true,
    showDepartments: true,
    departmentId: "",
    limit: 0,
  },
  partnerDirectory: {
    titleEn: "Partners",
    titleAr: "الشركاء",
    subtitleEn: "",
    subtitleAr: "",
    partnerProgramSlug: "",
    layout: "grid",
    showSearch: true,
    categorySlug: "",
    locationFilter: "",
    limit: 0,
    showMap: false,
  },
};

function blankDefaultStrings<T>(value: T): T {
  if (typeof value === "string") return "" as T;
  if (Array.isArray(value)) return value.map(blankDefaultStrings) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([key, entry]) => [
        key,
        blankDefaultStrings(entry),
      ])
    ) as T;
  }
  return value;
}

for (const key of Object.keys(BLOCK_DEFAULTS)) {
  BLOCK_DEFAULTS[key] = blankDefaultStrings(BLOCK_DEFAULTS[key]) as Record<string, unknown>;
}
