-- CreateTable
CREATE TABLE `Product` (
    `id` VARCHAR(191) NOT NULL,
    `locale` VARCHAR(10) NOT NULL DEFAULT 'en-us',
    `slug` VARCHAR(255) NOT NULL,
    `productTitle` VARCHAR(191) NOT NULL,
    `sku` VARCHAR(64) NULL,
    `priceValue` DECIMAL(12, 2) NULL,
    `priceCurrency` VARCHAR(3) NULL,
    `availability` VARCHAR(32) NULL,
    `stockStatus` VARCHAR(32) NULL,
    `brand` VARCHAR(128) NULL,
    `category` VARCHAR(128) NULL,
    `categories` JSON NULL,
    `tags` JSON NULL,
    `collectionSlugs` JSON NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'published',
    `sourceType` VARCHAR(16) NULL,
    `sourceFile` VARCHAR(512) NULL,
    `payload` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Product_locale_slug_key`(`locale`, `slug`),
    INDEX `Product_slug_idx`(`slug`),
    INDEX `Product_locale_idx`(`locale`),
    INDEX `Product_locale_brand_idx`(`locale`, `brand`),
    INDEX `Product_locale_category_idx`(`locale`, `category`),
    INDEX `Product_locale_status_idx`(`locale`, `status`),
    INDEX `Product_locale_stockStatus_idx`(`locale`, `stockStatus`),
    INDEX `Product_locale_priceValue_idx`(`locale`, `priceValue`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
