"use client";

import {
  Layout,
  Type,
  Image,
  Images,
  HelpCircle,
  Star,
  DollarSign,
  Megaphone,
  Video,
  FileText,
  Package,
  Hotel,
  Code,
  MoveVertical,
  Minus,
  Box,
  LayoutGrid,
  Mail,
  GalleryHorizontal,
  List,
  Link2,
  Columns2,
  Layers,
  Pin,
  UserPlus,
  FormInput,
  ListOrdered,
  MailPlus,
  Lock,
  Search,
  Filter,
  FolderTree,
  History,
  Calculator,
  BookOpen,
  Activity,
  Users,
  Handshake,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const ICON_MAP: Record<string, LucideIcon> = {
  layout: Layout,
  type: Type,
  image: Image,
  images: Images,
  "help-circle": HelpCircle,
  star: Star,
  "dollar-sign": DollarSign,
  megaphone: Megaphone,
  video: Video,
  "file-text": FileText,
  package: Package,
  hotel: Hotel,
  code: Code,
  "move-vertical": MoveVertical,
  minus: Minus,
  box: Box,
  "layout-grid": LayoutGrid,
  mail: Mail,
  "gallery-horizontal": GalleryHorizontal,
  list: List,
  link: Link2,
  columns: Columns2,
  layers: Layers,
  pin: Pin,
  "user-plus": UserPlus,
  "form-input": FormInput,
  "list-ordered": ListOrdered,
  "mail-plus": MailPlus,
  lock: Lock,
  search: Search,
  filter: Filter,
  "folder-tree": FolderTree,
  history: History,
  calculator: Calculator,
  "book-open": BookOpen,
  activity: Activity,
  users: Users,
  handshake: Handshake,
};

type Props = {
  icon: string;
  className?: string;
};

export function BlockTypeIcon({ icon, className }: Props) {
  const Icon = ICON_MAP[icon] ?? Box;
  return <Icon className={cn("h-5 w-5", className)} />;
}
