import type { DemoSampleData } from "@/features/setup/demo-import/types";
import { DEMO_PLACEHOLDER, demoMedia } from "@/seeds/demo-profiles/shared";

const HERO = "/demo/safar/hero.svg";

export const safarMediaFiles = [
  demoMedia("hero", HERO, "Safar Al-Madina Travel Agency"),
  demoMedia("dest-1", DEMO_PLACEHOLDER, "Makkah destination", "وجهة مكة"),
  demoMedia("dest-2", DEMO_PLACEHOLDER, "Madinah destination", "وجهة المدينة"),
  demoMedia("dest-3", DEMO_PLACEHOLDER, "Dubai skyline", "أفق دبي"),
  demoMedia("dest-4", DEMO_PLACEHOLDER, "Turkey travel", "سفر تركيا"),
  demoMedia("dest-5", DEMO_PLACEHOLDER, "Maldives resort", "منتجع المالديف"),
  demoMedia("dest-6", DEMO_PLACEHOLDER, "European tour", "جولة أوروبية"),
  demoMedia("dest-7", DEMO_PLACEHOLDER, "Adventure travel", "سفر مغامرات"),
  demoMedia("dest-8", DEMO_PLACEHOLDER, "Cultural experience", "تجربة ثقافية"),
  demoMedia("dest-9", DEMO_PLACEHOLDER, "Luxury vacation", "عطلة فاخرة"),
  demoMedia("dest-10", DEMO_PLACEHOLDER, "Family holiday", "عطلة عائلية"),
  demoMedia("dest-11", DEMO_PLACEHOLDER, "Honeymoon package", "باقة شهر العسل"),
  demoMedia("dest-12", DEMO_PLACEHOLDER, "Religious tourism", "سياحة دينية"),
  demoMedia("pkg-family", DEMO_PLACEHOLDER, "Family holiday package", "باقة عطلة عائلية"),
  demoMedia("pkg-honeymoon", DEMO_PLACEHOLDER, "Honeymoon package", "باقة شهر العسل"),
  demoMedia("hotel-1", DEMO_PLACEHOLDER, "Makkah hotel", "فندق مكة"),
  demoMedia("hotel-2", DEMO_PLACEHOLDER, "Madinah hotel", "فندق المدينة"),
];

export const safarSampleData: DemoSampleData = {
  faqSets: [
    {
      slug: "booking",
      title: "Booking FAQ",
      items: [
        {
          question: "How do I book a tour package?",
          answer: "Contact us via the inquiry form or phone. Our travel specialists will create a personalized itinerary based on your preferences and budget.",
        },
        {
          question: "What payment methods do you accept?",
          answer: "We accept bank transfer, credit cards, and installment plans for select packages. Details are provided during booking.",
        },
      ],
    },
    {
      slug: "visas",
      title: "Visa FAQ",
      items: [
        {
          question: "Do you provide visa assistance?",
          answer: "Yes. We offer visa guidance and documentation support for international destinations included in our packages.",
        },
      ],
    },
    {
      slug: "packages",
      title: "Packages FAQ",
      items: [
        {
          question: "Can packages be customized?",
          answer: "Absolutely. Every package can be tailored to your travel dates, group size, accommodation preferences, and activities.",
        },
      ],
    },
  ],
  testimonials: [
    {
      name: "Fatima Al-Zahra",
      location: "Dubai, UAE",
      rating: 5,
      content: "Our family Umrah package was perfectly organized. Every detail was handled with care and professionalism.",
    },
    {
      name: "James Wilson",
      location: "London, UK",
      rating: 5,
      content: "Safar Al-Madina planned our honeymoon to the Maldives flawlessly. Unforgettable experience!",
    },
    {
      name: "Mohammed Al-Sayed",
      location: "Riyadh, KSA",
      rating: 5,
      content: "Excellent corporate travel management. Reliable, transparent, and always responsive to our needs.",
    },
    {
      name: "Elena Rodriguez",
      location: "Madrid, Spain",
      rating: 5,
      content: "The European cultural tour exceeded our expectations. Authentic experiences and wonderful guides.",
    },
    {
      name: "Aisha Khan",
      location: "Abu Dhabi, UAE",
      rating: 5,
      content: "Adventure travel package to Turkey was thrilling and well-organized. Highly recommend Safar Al-Madina!",
    },
    {
      name: "David Thompson",
      location: "Sydney, Australia",
      rating: 5,
      content: "From flight booking to hotel arrangements, everything was seamless. A trusted travel partner.",
    },
  ],
  testimonialCollections: [
    {
      slug: "safar-travelers",
      title: "Traveler Reviews",
      testimonialIndexes: [0, 1, 2, 3, 4, 5],
    },
  ],
  galleries: [
    {
      slug: "safar-destinations",
      title: "Destinations Gallery",
      media: [
        { title: "Makkah", mediaKey: "dest-1" },
        { title: "Madinah", mediaKey: "dest-2" },
        { title: "Dubai", mediaKey: "dest-3" },
        { title: "Turkey", mediaKey: "dest-4" },
        { title: "Maldives", mediaKey: "dest-5" },
        { title: "Europe", mediaKey: "dest-6" },
        { title: "Adventure", mediaKey: "dest-7" },
        { title: "Cultural Tours", mediaKey: "dest-8" },
        { title: "Luxury", mediaKey: "dest-9" },
        { title: "Family Holidays", mediaKey: "dest-10" },
        { title: "Honeymoon", mediaKey: "dest-11" },
        { title: "Religious Tourism", mediaKey: "dest-12" },
      ],
    },
  ],
  contentItems: [
    {
      slug: "family-holiday-dubai",
      contentTypeSlug: "catalog-items",
      title: "Family Holiday — Dubai",
      excerpt: "5-day family adventure with theme parks and desert safari.",
      description: "Includes flights, 4-star hotel, theme park tickets, and guided desert safari.",
      attributes: { duration: 5, price: 2499, currency: "USD", features: ["Theme parks", "Desert safari", "City tour"] },
      imageKey: "pkg-family",
      isFeatured: true,
    },
    {
      slug: "honeymoon-maldives",
      contentTypeSlug: "catalog-items",
      title: "Honeymoon — Maldives",
      excerpt: "7 nights in an overwater villa with all-inclusive dining.",
      description: "Romantic getaway with spa treatments, sunset cruise, and private dining.",
      attributes: { duration: 7, price: 4999, currency: "USD", features: ["Overwater villa", "All-inclusive", "Spa"] },
      imageKey: "pkg-honeymoon",
      isFeatured: true,
    },
    {
      slug: "umrah-package",
      contentTypeSlug: "catalog-items",
      title: "Umrah Package",
      excerpt: "10-day spiritual journey with premium hotels in Makkah and Madinah.",
      description: "Complete Umrah package with visa, flights, hotels, transport, and guided ziyarat.",
      attributes: { duration: 10, price: 1899, currency: "USD", features: ["Visa", "5-star hotels", "Guided ziyarat"] },
      imageKey: "dest-12",
      isFeatured: true,
    },
    {
      slug: "turkey-adventure",
      contentTypeSlug: "catalog-items",
      title: "Turkey Adventure Tour",
      excerpt: "8-day adventure through Istanbul, Cappadocia, and Pamukkale.",
      description: "Hot air balloon, historical sites, and authentic Turkish cuisine experiences.",
      attributes: { duration: 8, price: 1599, currency: "USD", features: ["Hot air balloon", "Historical sites", "Local cuisine"] },
      imageKey: "dest-4",
    },
    {
      slug: "europe-cultural",
      contentTypeSlug: "catalog-items",
      title: "European Cultural Experience",
      excerpt: "12-day tour through Paris, Rome, and Barcelona.",
      description: "Museums, architecture, local guides, and authentic cultural immersion.",
      attributes: { duration: 12, price: 3299, currency: "USD", features: ["Museums", "Local guides", "Cultural immersion"] },
      imageKey: "dest-6",
    },
    {
      slug: "luxury-dubai",
      contentTypeSlug: "catalog-items",
      title: "Luxury Dubai Escape",
      excerpt: "5 nights at a 5-star resort with yacht experience.",
      description: "Premium accommodation, private transfers, and exclusive experiences.",
      attributes: { duration: 5, price: 3999, currency: "USD", features: ["5-star resort", "Yacht", "Private transfers"] },
      imageKey: "dest-9",
    },
    {
      slug: "seasonal-winter-europe",
      contentTypeSlug: "catalog-items",
      title: "Winter Europe Holiday",
      excerpt: "7-day winter wonderland tour with Christmas markets.",
      description: "Festive markets, alpine scenery, and cozy accommodations.",
      attributes: { duration: 7, price: 2199, currency: "USD", features: ["Christmas markets", "Alpine scenery", "Festive tours"] },
      imageKey: "dest-8",
    },
    {
      slug: "group-corporate-retreat",
      contentTypeSlug: "catalog-items",
      title: "Corporate Group Retreat",
      excerpt: "Customizable team-building travel for corporate groups.",
      description: "Tailored itineraries with meeting facilities and team activities.",
      attributes: { duration: 4, price: 1299, currency: "USD", features: ["Team building", "Meeting facilities", "Custom itinerary"] },
      imageKey: "dest-3",
    },
    {
      slug: "makkah-hotel-5star",
      contentTypeSlug: "listings",
      title: "Makkah Premium Hotel",
      excerpt: "5-star hotel steps from the Haram.",
      description: "Luxury accommodation with Haram views, premium dining, and concierge service.",
      attributes: { city: "MAKKAH", stars: 5, distance: "200m from Haram", amenities: ["Haram view", "Premium dining", "Concierge"] },
      imageKey: "hotel-1",
    },
    {
      slug: "madinah-hotel-4star",
      contentTypeSlug: "listings",
      title: "Madinah Comfort Hotel",
      excerpt: "4-star hotel near Masjid Nabawi.",
      description: "Comfortable rooms with Nabawi proximity, shuttle service, and halal dining.",
      attributes: { city: "MADINAH", stars: 4, distance: "500m from Nabawi", amenities: ["Shuttle", "Halal dining", "Prayer facilities"] },
      imageKey: "hotel-2",
    },
    {
      slug: "travel-planning",
      contentTypeSlug: "offerings",
      title: "Travel Planning & Consultation",
      excerpt: "Personalized itinerary development and destination recommendations.",
      description: "Expert travel specialists design trips around your preferences and budget.",
      attributes: { offeringType: "OTHER", icon: "fa-map", ctaLabel: "Consult Now", ctaHref: "/contact" },
      isFeatured: true,
    },
    {
      slug: "flight-booking",
      contentTypeSlug: "offerings",
      title: "Flight & Ticket Booking",
      excerpt: "Domestic and international flight reservations.",
      description: "Access to major airlines with multi-city and group booking options.",
      attributes: { offeringType: "OTHER", icon: "fa-plane", ctaLabel: "Book Flights", ctaHref: "/contact" },
    },
    {
      slug: "guided-tours",
      contentTypeSlug: "offerings",
      title: "Guided Tours & Experiences",
      excerpt: "Historical, cultural, and adventure tourism experiences.",
      description: "Connect with destinations through meaningful guided experiences.",
      attributes: { offeringType: "OTHER", icon: "fa-compass", ctaLabel: "Explore Tours", ctaHref: "/packages" },
    },
    {
      slug: "corporate-travel",
      contentTypeSlug: "offerings",
      title: "Corporate Travel Planning",
      excerpt: "Business travel management and group arrangements.",
      description: "Efficient corporate travel with schedule management and priority support.",
      attributes: { offeringType: "OTHER", icon: "fa-briefcase", ctaLabel: "Corporate Inquiry", ctaHref: "/contact" },
    },
  ],
  formTemplates: [
    {
      slug: "safar-inquiry",
      name: "Travel Inquiry Form",
      category: "GENERAL",
      definition: {
        fields: [
          { id: "name", type: "text", label: "Full Name", required: true },
          { id: "email", type: "email", label: "Email", required: true },
          { id: "phone", type: "phone", label: "Phone", required: true },
          { id: "destination", type: "text", label: "Preferred Destination", required: false },
          { id: "dates", type: "text", label: "Travel Dates", required: false },
          { id: "travelers", type: "number", label: "Number of Travelers", required: false },
          { id: "budget", type: "text", label: "Budget Range", required: false },
          { id: "message", type: "textarea", label: "Additional Details", required: false },
        ],
      },
    },
  ],
  postCategories: [
    { slug: "destinations", name: "Destinations"},
    { slug: "travel-tips", name: "Travel Tips"},
  ],
  posts: [
    {
      slug: "top-destinations-2026",
      title: "Top Travel Destinations for 2026",
      excerpt: "Discover the most inspiring destinations our travelers are booking this year.",
      content: "<p>From the spiritual beauty of Makkah and Madinah to the turquoise waters of the Maldives, 2026 offers incredible travel opportunities. Our specialists share their top picks for families, couples, and adventure seekers.</p>",
      imageKey: "dest-5",
      categorySlug: "destinations",
    },
    {
      slug: "umrah-planning-guide",
      title: "Complete Umrah Planning Guide",
      excerpt: "Everything you need to know before your spiritual journey.",
      content: "<p>Planning Umrah requires attention to visa requirements, hotel proximity, transport arrangements, and guided ziyarat. Safar Al-Madina provides end-to-end support for a seamless spiritual experience.</p>",
      imageKey: "dest-12",
      categorySlug: "travel-tips",
    },
    {
      slug: "family-travel-tips",
      title: "Family Travel Tips for Stress-Free Holidays",
      excerpt: "Make your next family vacation enjoyable for everyone.",
      content: "<p>Choose destinations with family-friendly activities, book accommodations with connecting rooms, and plan rest days between excursions. Our family packages handle all the details.</p>",
      imageKey: "dest-10",
      categorySlug: "travel-tips",
    },
    {
      slug: "honeymoon-destinations",
      title: "Best Honeymoon Destinations",
      excerpt: "Romantic getaways for newlyweds seeking unforgettable memories.",
      content: "<p>The Maldives, Bali, Santorini, and Dubai top our honeymoon recommendations. Each offers unique romance — overwater villas, sunset cruises, and private dining experiences.</p>",
      imageKey: "dest-11",
      categorySlug: "destinations",
    },
    {
      slug: "visa-travel-guide",
      title: "Visa Requirements: A Traveler's Guide",
      excerpt: "Navigate visa requirements for popular international destinations.",
      content: "<p>Visa requirements vary by nationality and destination. Our team provides up-to-date guidance and documentation support to ensure smooth travel preparations.</p>",
      imageKey: "dest-3",
      categorySlug: "travel-tips",
    },
  ],
};
