/** Built-in synonym groups (token → alternate terms). Merged with admin `smart.synonyms`. */
export const DEFAULT_SEARCH_SYNONYMS: Record<string, string[]> = {
  seo: ["search engine optimization", "search engine"],
  cms: ["content management system", "content"],
  ux: ["user experience"],
  ui: ["user interface"],
  blog: ["article", "post", "posts"],
  product: ["item", "products", "merchandise"],
  package: ["packages", "bundle", "tour"],
  collection: ["category", "group", "catalog"],
  page: ["pages", "landing"],
  post: ["article", "blog"],
  sale: ["discount", "offer", "deals"],
  pricing: ["price", "cost", "rates"],
  support: ["help", "assistance", "contact"],
  translate: ["localization", "i18n", "locale"],
  faq: ["questions", "help", "faqs"],
  search: ["find", "lookup", "query"],
  catalog: ["shop", "store", "products"],
  media: ["image", "images", "file", "files"],
  admin: ["dashboard", "settings", "backend"],
};
