/**
 * CI architecture contract for admin routes.
 * expectedActions live in ADMIN_PAGE_CONFIGS (via configKey), not here.
 */

import type { AdminPageMode } from "@/config/admin-page-config";
import type { AdminPageConfigKey } from "@/config/admin-page-configs";

export type AdminRegistrationStrategy =
  | "provider"
  | "patch"
  | "hook"
  | "child-handoff"
  | "none";

export type AdminActionInventoryEntry = {
  routePattern: string;
  mode: AdminPageMode;
  /** Key into ADMIN_PAGE_CONFIGS — runtime expectedActions source of truth. */
  configKey: AdminPageConfigKey;
  registrationStrategy: AdminRegistrationStrategy;
  handoffScopes?: string[];
  notes?: string;
};

export const ADMIN_ACTION_INVENTORY: AdminActionInventoryEntry[] = [
  { routePattern: "/admin", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/announcement-bar", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/catalog-collections", mode: "editor", configKey: "collectionsEditor", registrationStrategy: "hook" },
  { routePattern: "/admin/catalog-products", mode: "editor", configKey: "productEditor", registrationStrategy: "patch" },
  { routePattern: "/admin/catalog-taxonomy", mode: "settings", configKey: "settingsSavePublish", registrationStrategy: "hook" },
  { routePattern: "/admin/catalog/navigation", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/catalog/settings", mode: "settings", configKey: "settingsSavePublish", registrationStrategy: "hook" },
  { routePattern: "/admin/catalog/sync", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/categories", mode: "editor", configKey: "collectionsEditor", registrationStrategy: "hook" },
  { routePattern: "/admin/collections", mode: "editor", configKey: "collectionsEditor", registrationStrategy: "hook" },
  { routePattern: "/admin/communications", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/company", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/content", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/content-builder", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/content/[typeSlug]", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/content/[typeSlug]/[id]", mode: "editor", configKey: "contentItemEditor", registrationStrategy: "provider", handoffScopes: ["seo-tab"], notes: "Parent editor; SEO tab uses child-handoff via useAdminPageActions priority" },
  { routePattern: "/admin/content/[typeSlug]/new", mode: "editor", configKey: "contentItemEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/content/types", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/content/types/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/content/types/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/database", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/demo-profiles", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/demo-profiles/[slug]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/documentation", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/documentation/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/documentation/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/faqs", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/faqs/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/faqs/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/footer", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/form-submissions", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/form-submissions/[id]", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/forms", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/forms/[id]", mode: "editor", configKey: "formDesigner", registrationStrategy: "hook" },
  { routePattern: "/admin/forms/analytics", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/forms/new", mode: "editor", configKey: "formDesigner", registrationStrategy: "hook" },
  { routePattern: "/admin/gallery", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/gallery/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/gallery/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/header", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/help", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/hotels", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/hotels/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/hotels/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/inquiries", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/inquiries/[id]", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/knowledge-base", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/knowledge-base/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/knowledge-base/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/languages", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/marketing/ad-accounts", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/marketing/analytics", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/marketing/attribution", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/marketing/automation", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing/campaigns", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing/conversions", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing/integrations", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/marketing/landing-pages", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/marketing/leads", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/marketing/platforms", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing/publishing", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing/settings", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing/tracking", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/marketing/urls", mode: "settings", configKey: "settingsSaveOnly", registrationStrategy: "hook" },
  { routePattern: "/admin/media", mode: "editor", configKey: "mediaLibrary", registrationStrategy: "hook" },
  { routePattern: "/admin/newsletter", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/packages", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/packages/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/packages/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/pages", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/pages/[id]", mode: "editor", configKey: "cmsPageEditor", registrationStrategy: "provider", handoffScopes: ["seo-tab"], notes: "Parent editor; SEO tab uses child-handoff via useAdminPageActions priority" },
  { routePattern: "/admin/pages/new", mode: "editor", configKey: "cmsPageEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/partners", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/partners/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/partners/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/performance", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/personalization", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/policies", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/popups", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/posts", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/posts/[id]", mode: "editor", configKey: "cmsPostEditor", registrationStrategy: "provider", handoffScopes: ["seo-tab"], notes: "Parent editor; SEO tab uses child-handoff via useAdminPageActions priority" },
  { routePattern: "/admin/posts/authors", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/posts/categories", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/posts/new", mode: "editor", configKey: "cmsPostEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/posts/tags", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/preloader", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/presets", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/pricing-calculators", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/pricing-calculators/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/pricing-calculators/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/pricing-plans", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/pricing-plans/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/pricing-plans/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/product-listing-filters", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/products", mode: "editor", configKey: "productEditor", registrationStrategy: "patch" },
  { routePattern: "/admin/releases", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/releases/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/releases/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/seo", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/404", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/analysis", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/assistant", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/audit", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/autofill", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/automation", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/content", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/google", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/google-tags", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/history", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/integrations", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/issues", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/metadata", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/monitoring", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/recommendations", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/redirects", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/reports", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/robots", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/rules", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/schemas", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence/ai", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence/authority", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence/content", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence/entity-graph", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence/linking", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence/performance", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-intelligence/schema", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/automation", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/content", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/entities", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/google", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/monitoring", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/operations", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/operations/[id]", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/overview", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/pages", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/search-operations/settings", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/settings", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/setup", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/sitemap", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/structured-data", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/seo/tasks", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/tasks/today", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/tasks/week", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/technical", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/seo/templates", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/services", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/services/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/services/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/settings", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/settings/account", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/settings/email-accounts", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/settings/portal", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/settings/search", mode: "settings", configKey: "searchSettings", registrationStrategy: "hook" },
  { routePattern: "/admin/settings/site", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/settings/staff", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/settings/whatsapp", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/status", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/status/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/status/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/studio", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/surveys", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/surveys/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/surveys/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/team", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/team/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/team/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/terms", mode: "dashboard", configKey: "dashboard", registrationStrategy: "none" },
  { routePattern: "/admin/testimonials", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/testimonials/collections", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/testimonials/collections/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/testimonials/collections/new", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
  { routePattern: "/admin/theme", mode: "editor", configKey: "themeStudio", registrationStrategy: "provider" },
  { routePattern: "/admin/translations", mode: "settings", configKey: "settingsSaveCancel", registrationStrategy: "hook" },
  { routePattern: "/admin/users", mode: "list", configKey: "list", registrationStrategy: "none" },
  { routePattern: "/admin/users/[id]", mode: "editor", configKey: "entityEditor", registrationStrategy: "provider" },
];

export function getInventoryEntry(routePattern: string): AdminActionInventoryEntry | undefined {
  return ADMIN_ACTION_INVENTORY.find((e) => e.routePattern === routePattern);
}
