import type { HelpWorkflow } from "@/features/help/types";

export const HELP_WORKFLOWS: HelpWorkflow[] = [
  {
    id: "workflow-first-setup",
    title: "First Time Setup",
    summary: "Orient yourself after installation and prepare the basics.",
    readingTime: 5,
    difficulty: "beginner",
    badges: ["recommended", "required"],
    keywords: ["setup", "onboarding", "getting started", "install"],
    steps: [
      { id: "wfs-1", type: "topic", label: "Open Dashboard", topicId: "topic-dashboard" },
      { id: "wfs-2", type: "topic", label: "Site access", topicId: "topic-site-access" },
      { id: "wfs-3", type: "route", label: "Set site access", href: "/admin/settings/site" },
      { id: "wfs-4", type: "checklist", label: "Launch checklist", checklistId: "checklist-launch" },
    ],
  },
  {
    id: "workflow-create-page",
    title: "Create a Page",
    summary: "Add and publish a new CMS page with blocks.",
    readingTime: 2,
    difficulty: "beginner",
    badges: ["recommended"],
    navItemIds: ["pages"],
    keywords: ["page", "cms", "builder", "blocks"],
    steps: [
      { id: "wcp-1", type: "topic", label: "Pages", topicId: "topic-pages" },
      { id: "wcp-2", type: "route", label: "Open Pages", href: "/admin/pages" },
      { id: "wcp-3", type: "topic", label: "Studio preview", topicId: "topic-studio" },
    ],
  },
  {
    id: "workflow-add-products",
    title: "Add Products",
    summary: "Create catalog products with media and pricing.",
    readingTime: 3,
    difficulty: "beginner",
    badges: ["recommended"],
    navItemIds: ["products"],
    featureFlags: ["catalog"],
    keywords: ["products", "catalog", "store", "sku"],
    steps: [
      { id: "wap-1", type: "topic", label: "Products", topicId: "topic-products" },
      { id: "wap-2", type: "route", label: "Open Products", href: "/admin/products" },
      { id: "wap-3", type: "checklist", label: "Store checklist", checklistId: "checklist-store" },
    ],
  },
  {
    id: "workflow-customize-design",
    title: "Customize Design",
    summary: "Theme, header, footer, and Studio preview.",
    readingTime: 4,
    difficulty: "beginner",
    badges: ["recommended"],
    navItemIds: ["theme", "studio"],
    keywords: ["theme", "design", "colors", "header", "footer"],
    steps: [
      { id: "wcd-1", type: "topic", label: "Theme", topicId: "topic-theme" },
      { id: "wcd-2", type: "route", label: "Open Theme", href: "/admin/theme" },
      { id: "wcd-3", type: "route", label: "Open Studio", href: "/admin/studio" },
    ],
  },
  {
    id: "workflow-configure-forms",
    title: "Configure Forms",
    summary: "Collect leads and route notifications to email.",
    readingTime: 3,
    difficulty: "intermediate",
    badges: ["launch-required"],
    navItemIds: ["form-templates"],
    featureFlags: ["forms"],
    keywords: ["forms", "leads", "submissions", "email"],
    steps: [
      { id: "wcf-1", type: "topic", label: "Form templates", topicId: "topic-form-templates" },
      { id: "wcf-2", type: "route", label: "Open Forms", href: "/admin/forms" },
      { id: "wcf-3", type: "route", label: "Email Accounts", href: "/admin/settings/email-accounts" },
    ],
  },
  {
    id: "workflow-enable-languages",
    title: "Enable Languages",
    summary: "Turn on locales, translate content, verify RTL.",
    readingTime: 4,
    difficulty: "intermediate",
    badges: ["recommended"],
    navItemIds: ["languages"],
    keywords: ["languages", "i18n", "rtl", "translation"],
    steps: [
      { id: "wel-1", type: "topic", label: "Languages", topicId: "topic-languages" },
      { id: "wel-2", type: "route", label: "Open Languages", href: "/admin/languages" },
      { id: "wel-3", type: "checklist", label: "Multilingual checklist", checklistId: "checklist-multilingual" },
    ],
  },
  {
    id: "workflow-seo-setup",
    title: "SEO Setup",
    summary: "Metadata, sitemap, and search engine basics.",
    readingTime: 3,
    difficulty: "intermediate",
    badges: ["launch-required"],
    navItemIds: ["seo-overview"],
    featureFlags: ["seo"],
    keywords: ["seo", "metadata", "sitemap", "robots"],
    steps: [
      { id: "wse-1", type: "topic", label: "SEO Overview", topicId: "topic-seo-overview" },
      { id: "wse-2", type: "topic", label: "Metadata", topicId: "topic-seo-metadata" },
      { id: "wse-3", type: "route", label: "Sitemap", href: "/admin/seo/sitemap" },
      { id: "wse-4", type: "checklist", label: "SEO launch checklist", checklistId: "checklist-seo-launch" },
    ],
  },
  {
    id: "workflow-launch-website",
    title: "Launch Website",
    summary: "Final checks before removing Coming Soon.",
    readingTime: 5,
    difficulty: "beginner",
    badges: ["launch-required", "required"],
    navItemIds: ["site-access"],
    keywords: ["launch", "go live", "publish", "checklist"],
    steps: [
      { id: "wlw-1", type: "topic", label: "Site access", topicId: "topic-site-access" },
      { id: "wlw-2", type: "checklist", label: "Website Launch checklist", checklistId: "checklist-launch" },
      { id: "wlw-3", type: "route", label: "Site Access", href: "/admin/settings/site" },
    ],
  },
  {
    id: "workflow-configure-email",
    title: "Configure Email",
    summary: "Connect SMTP/provider so forms and alerts deliver.",
    readingTime: 2,
    difficulty: "intermediate",
    badges: ["launch-required"],
    navItemIds: ["email-accounts"],
    keywords: ["email", "smtp", "notifications", "resend"],
    steps: [
      { id: "wce-1", type: "topic", label: "Email Accounts", topicId: "topic-email-accounts" },
      { id: "wce-2", type: "route", label: "Open Email Accounts", href: "/admin/settings/email-accounts" },
    ],
  },
  {
    id: "workflow-configure-marketing",
    title: "Configure Marketing",
    summary: "Connect platforms and review the marketing hub.",
    readingTime: 3,
    difficulty: "intermediate",
    navItemIds: ["marketing-dashboard"],
    keywords: ["marketing", "social", "campaigns"],
    steps: [
      { id: "wcm-1", type: "topic", label: "Marketing Hub", topicId: "topic-marketing-dashboard" },
      { id: "wcm-2", type: "topic", label: "Platforms", topicId: "topic-marketing-platforms" },
      { id: "wcm-3", type: "route", label: "Open Marketing", href: "/admin/marketing" },
    ],
  },
];
