import type { HelpWorkflow } from "@/features/help/types";

export const HELP_WORKFLOWS: HelpWorkflow[] = [
  {
    id: "workflow-first-setup",
    title: "First Time Setup",
    summary: "Orient yourself after installation and prepare the basics.",
    readingTime: 5,
    difficulty: "beginner",
    badges: ["recommended", "required"],
    keywords: ["setup", "onboarding", "getting started", "install"],
    steps: [
      { id: "wfs-1", type: "topic", label: "Open Dashboard", topicId: "topic-dashboard" },
      { id: "wfs-2", type: "topic", label: "Site access", topicId: "topic-site-access" },
      { id: "wfs-3", type: "route", label: "Set site access", href: "/admin/settings/site" },
      { id: "wfs-4", type: "checklist", label: "Launch checklist", checklistId: "checklist-launch" },
    ],
  },
  {
    id: "workflow-create-page",
    title: "Create a Page",
    summary: "Add and publish a new CMS page with blocks.",
    readingTime: 2,
    difficulty: "beginner",
    badges: ["recommended"],
    navItemIds: ["pages"],
    keywords: ["page", "cms", "builder", "blocks"],
    steps: [
      { id: "wcp-1", type: "topic", label: "Pages", topicId: "topic-pages" },
      { id: "wcp-2", type: "route", label: "Open Pages", href: "/admin/pages" },
      { id: "wcp-3", type: "topic", label: "Studio preview", topicId: "topic-studio" },
    ],
  },
  {
    id: "workflow-add-products",
    title: "Add Products",
    summary: "Create catalog products with media and pricing.",
    readingTime: 3,
    difficulty: "beginner",
    badges: ["recommended"],
    navItemIds: ["products"],
    featureFlags: ["catalog"],
    keywords: ["products", "catalog", "store", "sku"],
    steps: [
      { id: "wap-1", type: "topic", label: "Products", topicId: "topic-products" },
      { id: "wap-2", type: "route", label: "Open Products", href: "/admin/products" },
      { id: "wap-3", type: "checklist", label: "Store checklist", checklistId: "checklist-store" },
    ],
  },
  {
    id: "workflow-customize-design",
    title: "Customize Design",
    summary: "Theme, header, footer, and Studio preview.",
    readingTime: 4,
    difficulty: "beginner",
    badges: ["recommended"],
    navItemIds: ["theme", "studio"],
    keywords: ["theme", "design", "colors", "header", "footer"],
    steps: [
      { id: "wcd-1", type: "topic", label: "Theme", topicId: "topic-theme" },
      { id: "wcd-2", type: "route", label: "Open Theme", href: "/admin/theme" },
      { id: "wcd-3", type: "route", label: "Open Studio", href: "/admin/studio" },
    ],
  },
  {
    id: "workflow-configure-forms",
    title: "Configure Forms",
    summary: "Collect leads and route notifications to email.",
    readingTime: 3,
    difficulty: "intermediate",
    badges: ["launch-required"],
    navItemIds: ["form-templates"],
    featureFlags: ["forms"],
    keywords: ["forms", "leads", "submissions", "email"],
    steps: [
      { id: "wcf-1", type: "topic", label: "Form templates", topicId: "topic-form-templates" },
      { id: "wcf-2", type: "route", label: "Open Forms", href: "/admin/forms" },
      { id: "wcf-3", type: "route", label: "Email Accounts", href: "/admin/settings/email-accounts" },
    ],
  },
  {
    id: "workflow-enable-languages",
    title: "Enable Languages",
    summary: "Turn on locales, translate content, verify RTL.",
    readingTime: 4,
    difficulty: "intermediate",
    badges: ["recommended"],
    navItemIds: ["languages"],
    keywords: ["languages", "i18n", "rtl", "translation"],
    steps: [
      { id: "wel-1", type: "topic", label: "Languages", topicId: "topic-languages" },
      { id: "wel-2", type: "route", label: "Open Languages", href: "/admin/languages" },
      { id: "wel-3", type: "checklist", label: "Multilingual checklist", checklistId: "checklist-multilingual" },
    ],
  },
  {
    id: "workflow-seo-setup",
    title: "SEO Setup",
    summary: "Configure site information, search appearance, search engines, and defaults.",
    readingTime: 3,
    difficulty: "intermediate",
    badges: ["launch-required"],
    navItemIds: ["seo-overview"],
    featureFlags: ["seo"],
    keywords: ["seo", "metadata", "sitemap", "robots", "indexnow", "setup"],
    steps: [
      { id: "wse-0", type: "route", label: "Open SEO Setup", href: "/admin/seo/setup" },
      { id: "wse-1", type: "topic", label: "SEO Dashboard", topicId: "topic-seo-overview" },
      { id: "wse-2", type: "topic", label: "Metadata", topicId: "topic-seo-metadata" },
      { id: "wse-3", type: "route", label: "Sitemap", href: "/admin/seo/sitemap" },
      {
        id: "wse-3b",
        type: "route",
        label: "Structured data",
        href: "/admin/seo/structured-data?tab=audit",
      },
      {
        id: "wse-3c",
        type: "topic",
        label: "Search Engines (IndexNow & Bing)",
        topicId: "topic-seo-integrations",
      },
      { id: "wse-4", type: "checklist", label: "SEO launch checklist", checklistId: "checklist-seo-launch" },
    ],
  },
  {
    id: "workflow-launch-website",
    title: "Launch Website",
    summary: "Final checks before removing Coming Soon.",
    readingTime: 5,
    difficulty: "beginner",
    badges: ["launch-required", "required"],
    navItemIds: ["site-access"],
    keywords: ["launch", "go live", "publish", "checklist"],
    steps: [
      { id: "wlw-1", type: "topic", label: "Site access", topicId: "topic-site-access" },
      { id: "wlw-2", type: "checklist", label: "Website Launch checklist", checklistId: "checklist-launch" },
      { id: "wlw-3", type: "route", label: "Site Access", href: "/admin/settings/site" },
    ],
  },
  {
    id: "workflow-configure-email",
    title: "Configure Email",
    summary: "Connect SMTP/provider so forms and alerts deliver.",
    readingTime: 2,
    difficulty: "intermediate",
    badges: ["launch-required"],
    navItemIds: ["email-accounts"],
    keywords: ["email", "smtp", "notifications", "resend"],
    steps: [
      { id: "wce-1", type: "topic", label: "Email Accounts", topicId: "topic-email-accounts" },
      { id: "wce-2", type: "route", label: "Open Email Accounts", href: "/admin/settings/email-accounts" },
    ],
  },
  {
    id: "workflow-configure-marketing",
    title: "Configure Marketing",
    summary: "Create campaigns, connect advertising platforms, and review marketing intelligence.",
    readingTime: 5,
    difficulty: "intermediate",
    navItemIds: ["marketing-dashboard", "marketing-campaigns", "marketing-platforms"],
    keywords: ["marketing", "campaigns", "ads", "attribution"],
    steps: [
      { id: "wcm-1", type: "topic", label: "Marketing Overview", topicId: "topic-marketing-dashboard" },
      { id: "wcm-2", type: "topic", label: "Campaigns", topicId: "topic-marketing-campaigns" },
      { id: "wcm-3", type: "topic", label: "Advertising Platforms", topicId: "topic-marketing-platforms" },
      {
        id: "wcm-3b",
        type: "workflow",
        label: "Connect LinkedIn advertising",
        workflowId: "workflow-linkedin-ads-setup",
      },
      { id: "wcm-4", type: "route", label: "Open Marketing Overview", href: "/admin/marketing" },
    ],
  },
  {
    id: "workflow-google-ads-setup",
    title: "Set up Google Ads (SEO Google)",
    summary:
      "Connect OAuth and Ads API credentials under SEO → Google → Ads, sync Ad Accounts in Marketing, link campaigns, and use the scoreboard — one SEO-owned connection.",
    readingTime: 12,
    difficulty: "intermediate",
    navItemIds: [
      "seo-google",
      "marketing-ad-accounts",
      "marketing-campaigns",
      "marketing-platforms",
    ],
    keywords: [
      "google ads",
      "oauth",
      "developer token",
      "mcc",
      "campaign linking",
      "gclid",
      "scoreboard",
    ],
    steps: [
      {
        id: "wga-1",
        type: "topic",
        label: "SEO Google Ads (credentials & OAuth)",
        topicId: "topic-seo-google",
      },
      {
        id: "wga-2",
        type: "route",
        label: "Open SEO → Google → Ads",
        href: "/admin/seo/google?tab=ads",
      },
      {
        id: "wga-3",
        type: "route",
        label: "Connect OAuth and save developer token + MCC + customer",
        href: "/admin/seo/google?tab=ads#configuration",
      },
      {
        id: "wga-3b",
        type: "topic",
        label: "If you see 403 permission errors",
        topicId: "topic-seo-google",
      },
      {
        id: "wga-4",
        type: "topic",
        label: "Ad Accounts (sync & select customer)",
        topicId: "topic-marketing-ad-accounts",
      },
      {
        id: "wga-5",
        type: "route",
        label: "Open Ad Accounts and sync",
        href: "/admin/marketing/ad-accounts",
      },
      {
        id: "wga-6",
        type: "topic",
        label: "Campaigns (link & scoreboard)",
        topicId: "topic-marketing-campaigns",
      },
      {
        id: "wga-7",
        type: "route",
        label: "Open Campaigns",
        href: "/admin/marketing/campaigns",
      },
      {
        id: "wga-8",
        type: "topic",
        label: "Marketing Platforms (status only)",
        topicId: "topic-marketing-platforms",
      },
    ],
  },
  {
    id: "workflow-linkedin-ads-setup",
    title: "Connect LinkedIn advertising",
    summary:
      "Create a LinkedIn Developer app, register the Marketing OAuth callback, save Client ID/Secret under Advertising Platforms, Connect LinkedIn, and verify the connection.",
    readingTime: 8,
    difficulty: "intermediate",
    navItemIds: ["marketing-platforms", "marketing-tracking", "marketing-campaigns"],
    keywords: [
      "linkedin",
      "linkedin ads",
      "oauth",
      "client id",
      "client secret",
      "r_ads",
      "rw_ads",
      "advertising platforms",
    ],
    steps: [
      {
        id: "wli-1",
        type: "topic",
        label: "Advertising Platforms (LinkedIn credentials & OAuth)",
        topicId: "topic-marketing-platforms",
      },
      {
        id: "wli-2",
        type: "route",
        label: "Open Advertising Platforms → LinkedIn",
        href: "/admin/marketing/platforms?tab=linkedin",
      },
      {
        id: "wli-3",
        type: "route",
        label: "Save Client ID and Client Secret",
        href: "/admin/marketing/platforms?tab=linkedin",
      },
      {
        id: "wli-4",
        type: "route",
        label: "Connect LinkedIn (OAuth)",
        href: "/api/marketing/oauth/linkedin/start",
      },
      {
        id: "wli-5",
        type: "route",
        label: "Optional: LinkedIn Partner ID (Insight Tag)",
        href: "/admin/marketing/tracking",
      },
      {
        id: "wli-6",
        type: "topic",
        label: "Campaigns (link / publish as needed)",
        topicId: "topic-marketing-campaigns",
      },
    ],
  },
];
