export type SearchLocale = "en" | "ar";

export const SEARCH_COPY = {
  en: {
    placeholder: "Search catalog, blog, pages, FAQs…",
    emptyTitle: "No results found",
    emptySub: "Try different keywords or clear filters.",
    startTitle: "Start typing to search",
    startSub: "Search across catalog, pages, posts, and more.",
    all: "All",
    search: "Search",
    suggestions: "Suggestions",
    results: "Results",
    recent: "Recent searches",
    popular: "Popular searches",
    trending: "Trending",
    history: "Search history",
    navigate: "↑↓ navigate",
    open: "↵ open",
    close: "esc close",
    typeMin: (n: number) => `Type at least ${n} characters for full results`,
    searching: "Searching…",
    pageTitle: "Search",
    pageSub: "Find pages, catalog items, collections, and blog posts.",
    resultCount: (n: number) => `${n} result${n === 1 ? "" : "s"}`,
    pressEnter: "Press Enter to search",
    clear: "Clear search",
    clearAllFilters: "Clear all filters",
    filtersActive: (n: number) => `${n} filter${n === 1 ? "" : "s"} active`,
    contentType: "Type",
    showMore: (n: number) => `Show ${n} more`,
    showLess: "Show less",
    searchError: "Search is temporarily unavailable. Try again.",
    tryRemovingFilters: "Try removing a filter or broadening your search.",
    loadMore: "Load more results",
    loadingMore: "Loading…",
  },
  ar: {
    placeholder: "ابحث في الفهرس والمدونة والصفحات والأسئلة…",
    emptyTitle: "لا توجد نتائج",
    emptySub: "جرّب كلمات مختلفة أو أزل عوامل التصفية.",
    startTitle: "ابدأ الكتابة للبحث",
    startSub: "ابحث في الفهرس والصفحات والمقالات والمزيد.",
    all: "الكل",
    search: "بحث",
    suggestions: "اقتراحات",
    results: "النتائج",
    recent: "عمليات البحث الأخيرة",
    popular: "عمليات بحث شائعة",
    trending: "رائج",
    history: "سجل البحث",
    navigate: "↑↓ للتنقل",
    open: "↵ للفتح",
    close: "esc للإغلاق",
    typeMin: (n: number) => `اكتب ${n} أحرف على الأقل للنتائج الكاملة`,
    searching: "جاري البحث…",
    pageTitle: "بحث",
    pageSub: "اعثر على الصفحات وعناصر الفهرس والمجموعات والمقالات.",
    resultCount: (n: number) => `${n} نتيجة`,
    pressEnter: "اضغط Enter للبحث",
    clear: "مسح البحث",
    clearAllFilters: "مسح جميع عوامل التصفية",
    filtersActive: (n: number) => `${n} عوامل تصفية نشطة`,
    contentType: "النوع",
    showMore: (n: number) => `عرض ${n} المزيد`,
    showLess: "عرض أقل",
    searchError: "البحث غير متاح مؤقتًا. حاول مرة أخرى.",
    tryRemovingFilters: "جرّب إزالة عامل تصفية أو توسيع البحث.",
    loadMore: "تحميل المزيد",
    loadingMore: "جاري التحميل…",
  },
} as const;

export function searchCopy(locale: string) {
  return SEARCH_COPY[locale === "ar" ? "ar" : "en"];
}
