import { z } from "zod";

export const companyInfoSchema = z.object({
  name: z.string().min(1),
  taglineEn: z.string().min(1),
  taglineAr: z.string().min(1),
  storyEn: z.string().min(1),
  storyAr: z.string().min(1),
  missionEn: z.string().min(1),
  missionAr: z.string().min(1),
  visionEn: z.string().min(1),
  visionAr: z.string().min(1),
  valuesEn: z.string().default("[]"),
  valuesAr: z.string().default("[]"),
  registrationNo: z.string().min(1),
  licenseInfo: z.string().min(1),
  addressEn: z.string().min(1),
  addressAr: z.string().min(1),
  phone: z.string().min(1),
  whatsapp: z.string().min(1),
  email: z.string().email(),
  officeHoursEn: z.string().min(1),
  officeHoursAr: z.string().min(1),
  socialLinks: z.string().default("{}"),
  trustBadges: z.string().default("[]"),
});
