import {
  Antenna,
  Battery,
  Bluetooth,
  Bookmark,
  Box,
  Boxes,
  Building2,
  Cable,
  Camera,
  CircleAlert,
  CircleCheck,
  Cloud,
  Cpu,
  Database,
  DoorOpen,
  ExternalLink,
  Eye,
  File,
  Filter,
  Flame,
  Folder,
  Globe,
  Grid2x2,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Image,
  Info,
  Key,
  Laptop,
  Layers,
  Link,
  List,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Monitor,
  Moon,
  Network,
  Package,
  Phone,
  Plug,
  Printer,
  Radio,
  Router,
  Search,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Speaker,
  Star,
  Sun,
  Tablet,
  Tag,
  User,
  Users,
  Video,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type CatalogNavLucideOption = {
  id: string;
  label: string;
  Icon: LucideIcon;
};

/** Picker options for catalog navigation (admin + storefront). */
export const CATALOG_NAV_LUCIDE_OPTIONS: CatalogNavLucideOption[] = [
  { id: "layers", label: "Layers", Icon: Layers },
  { id: "wifi", label: "WiFi", Icon: Wifi },
  { id: "server", label: "Switching", Icon: Server },
  { id: "camera", label: "Camera", Icon: Camera },
  { id: "shield", label: "Security", Icon: Shield },
  { id: "cloud", label: "Cloud", Icon: Cloud },
  { id: "router", label: "Router", Icon: Router },
  { id: "network", label: "Network", Icon: Network },
  { id: "package", label: "Package", Icon: Package },
  { id: "tag", label: "Tag", Icon: Tag },
  { id: "door-open", label: "Door", Icon: DoorOpen },
  { id: "hard-drive", label: "Storage", Icon: HardDrive },
  { id: "monitor", label: "Monitor", Icon: Monitor },
  { id: "cpu", label: "CPU", Icon: Cpu },
  { id: "cable", label: "Cable", Icon: Cable },
  { id: "megaphone", label: "New", Icon: Megaphone },
  { id: "radio", label: "Radio", Icon: Radio },
  { id: "antenna", label: "Antenna", Icon: Antenna },
  { id: "bluetooth", label: "Bluetooth", Icon: Bluetooth },
  { id: "smartphone", label: "Phone", Icon: Smartphone },
  { id: "tablet", label: "Tablet", Icon: Tablet },
  { id: "laptop", label: "Laptop", Icon: Laptop },
  { id: "printer", label: "Printer", Icon: Printer },
  { id: "headphones", label: "Audio", Icon: Headphones },
  { id: "speaker", label: "Speaker", Icon: Speaker },
  { id: "battery", label: "Battery", Icon: Battery },
  { id: "zap", label: "Power", Icon: Zap },
  { id: "plug", label: "Plug", Icon: Plug },
  { id: "lock", label: "Lock", Icon: Lock },
  { id: "key", label: "Key", Icon: Key },
  { id: "eye", label: "Eye", Icon: Eye },
  { id: "settings", label: "Settings", Icon: Settings },
  { id: "wrench", label: "Tools", Icon: Wrench },
  { id: "box", label: "Box", Icon: Box },
  { id: "boxes", label: "Boxes", Icon: Boxes },
  { id: "shopping-cart", label: "Cart", Icon: ShoppingCart },
  { id: "star", label: "Star", Icon: Star },
  { id: "heart", label: "Heart", Icon: Heart },
  { id: "home", label: "Home", Icon: Home },
  { id: "globe", label: "Globe", Icon: Globe },
  { id: "map-pin", label: "Location", Icon: MapPin },
  { id: "building", label: "Building", Icon: Building2 },
  { id: "users", label: "Users", Icon: Users },
  { id: "user", label: "User", Icon: User },
  { id: "mail", label: "Mail", Icon: Mail },
  { id: "phone", label: "Call", Icon: Phone },
  { id: "link", label: "Link", Icon: Link },
  { id: "external-link", label: "External", Icon: ExternalLink },
  { id: "search", label: "Search", Icon: Search },
  { id: "filter", label: "Filter", Icon: Filter },
  { id: "sliders-horizontal", label: "Sliders", Icon: SlidersHorizontal },
  { id: "grid-2x2", label: "Grid", Icon: Grid2x2 },
  { id: "list", label: "List", Icon: List },
  { id: "image", label: "Image", Icon: Image },
  { id: "video", label: "Video", Icon: Video },
  { id: "file", label: "File", Icon: File },
  { id: "folder", label: "Folder", Icon: Folder },
  { id: "database", label: "Database", Icon: Database },
  { id: "circle-check", label: "Check", Icon: CircleCheck },
  { id: "circle-alert", label: "Alert", Icon: CircleAlert },
  { id: "info", label: "Info", Icon: Info },
  { id: "bookmark", label: "Bookmark", Icon: Bookmark },
  { id: "flame", label: "Flame", Icon: Flame },
  { id: "sun", label: "Sun", Icon: Sun },
  { id: "moon", label: "Moon", Icon: Moon },
];

const OPTION_BY_ID = new Map(CATALOG_NAV_LUCIDE_OPTIONS.map((o) => [o.id, o.Icon]));

/** Extra aliases → canonical Lucide component (storefront resolution). */
const LUCIDE_ALIASES: Record<string, LucideIcon> = {
  category: Layers,
  brand: Tag,
  product: Package,
  "wi-fi": Wifi,
  wireless: Wifi,
  security: Shield,
  protect: Camera,
  switching: Server,
  switch: Server,
  door: DoorOpen,
  "door-access": DoorOpen,
  gateway: Cloud,
  harddrive: HardDrive,
  hosting: HardDrive,
  storage: HardDrive,
  power: Zap,
  integrations: Monitor,
  new: Megaphone,
  "whats-new": Megaphone,
  tool: Wrench,
  tools: Wrench,
  cart: ShoppingCart,
  location: MapPin,
  building2: Building2,
  call: Phone,
  external: ExternalLink,
  grid: Grid2x2,
  check: CircleCheck,
  alert: CircleAlert,
  audio: Headphones,
};

/**
 * Resolve a Lucide icon id / alias to a component.
 * Unknown names fall back to Layers.
 */
export function resolveCatalogNavLucide(icon?: string): LucideIcon {
  if (!icon) return Layers;
  const key = icon.trim().toLowerCase().replace(/\s+/g, "-");
  return OPTION_BY_ID.get(key) ?? LUCIDE_ALIASES[key] ?? Layers;
}
