import type { HelpInventoryPage } from "@/features/help/inventory/types";

/**
 * Page compositions inspected from real admin UI.
 * Keys are navItemId. Merged over nav-generated defaults.
 */
export const PAGE_INVENTORY_OVERRIDES: Record<string, Partial<HelpInventoryPage>> = {
  "seo-overview": {
    version: 1,
    pageKind: "dashboard",
    sectionIds: ["section-seo-snapshot"],
    actionIds: ["action-run-site-audit", "action-save"],
    componentIds: undefined,
    tableIds: undefined,
  },
  "seo-metadata": {
    version: 2,
    pageKind: "action",
    tabIds: [
      "tab-seo-metadata-overview",
      "tab-seo-metadata-global-tools",
      "tab-seo-metadata-integrations",
      "tab-seo-metadata-static",
    ],
    componentIds: ["component-seo-meta", "component-locale-fields", "component-media-picker"],
    actionIds: ["action-auto-fill-seo", "action-save"],
    sectionIds: ["section-shared-seo"],
  },
  "seo-content-audit": {
    version: 1,
    pageKind: "action",
    actionIds: ["action-analyze-content"],
    componentIds: undefined,
    tableIds: undefined,
    sectionIds: undefined,
  },
  "seo-technical-audit": {
    version: 1,
    pageKind: "dashboard",
    actionIds: ["action-save"],
    componentIds: undefined,
    tableIds: undefined,
  },
  "seo-issues": {
    version: 1,
    pageKind: "table",
    tableIds: ["table-seo-issues"],
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  "seo-recommendations": {
    version: 1,
    pageKind: "informational",
    actionIds: ["action-save"],
    componentIds: undefined,
    tableIds: undefined,
  },
  "seo-audit-history": {
    version: 1,
    pageKind: "table",
    tableIds: ["table-seo-audit-history"],
    actionIds: ["action-save"],
  },
  "seo-redirects": {
    version: 1,
    pageKind: "action",
    sectionIds: [
      "section-seo-routing-links",
      "section-seo-redirect-form",
      "section-seo-redirect-rules",
    ],
    fieldIds: ["field-redirect-from", "field-redirect-to", "field-redirect-type"],
    actionIds: ["action-add-redirect", "action-save", "action-delete"],
    componentIds: undefined,
    tableIds: undefined,
  },
  "seo-robots": {
    version: 1,
    pageKind: "action",
    fieldIds: ["field-robots-host", "field-robots-disallow", "field-robots-allow"],
    actionIds: ["action-save"],
    componentIds: undefined,
    tableIds: undefined,
  },
  "seo-sitemap": {
    version: 1,
    pageKind: "action",
    fieldIds: ["field-sitemap-exclude", "field-sitemap-extra"],
    tableIds: ["table-sitemap-urls"],
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  "seo-structured-data": {
    version: 1,
    pageKind: "action",
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  "seo-google": {
    version: 1,
    pageKind: "action",
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  "seo-integrations": {
    version: 1,
    pageKind: "action",
    tabIds: [
      "tab-seo-integrations-monitoring",
      "tab-seo-integrations-configure",
      "tab-seo-integrations-queue",
    ],
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  "seo-404": {
    version: 1,
    pageKind: "action",
    componentIds: ["component-locale-fields"],
    actionIds: ["action-save"],
  },
  "seo-rules": {
    version: 1,
    pageKind: "informational",
    actionIds: ["action-save"],
    componentIds: undefined,
    tableIds: undefined,
  },
  "seo-schemas": {
    version: 1,
    pageKind: "informational",
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  "seo-templates": {
    version: 1,
    pageKind: "informational",
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  pages: {
    version: 2,
    pageKind: "table",
    tabIds: ["tab-pages-marketing", "tab-pages-cms"],
    componentIds: ["component-admin-list"],
    sectionIds: undefined,
    actionIds: ["action-save", "action-publish", "action-preview", "action-duplicate", "action-delete"],
    tableIds: undefined,
  },
  "form-templates": {
    version: 1,
    pageKind: "table",
    tableIds: ["table-form-templates"],
    actionIds: ["action-save", "action-publish", "action-duplicate", "action-delete"],
    componentIds: undefined,
  },
  languages: {
    version: 1,
    pageKind: "action",
    sectionIds: ["section-languages-locale-cards"],
    fieldIds: ["field-locale-code", "field-locale-prefix", "field-locale-direction"],
    actionIds: ["action-save", "action-delete"],
    componentIds: undefined,
  },
  translations: {
    version: 1,
    pageKind: "action",
    tabIds: ["tab-translations-editor", "tab-translations-config"],
    dialogIds: ["dialog-translations-import"],
    actionIds: ["action-save"],
    componentIds: ["component-locale-fields"],
  },
  "site-access": {
    version: 1,
    pageKind: "action",
    sectionIds: ["section-site-visibility"],
    fieldIds: ["field-coming-soon-toggle"],
    dialogIds: ["dialog-reset-setup-wizard"],
    actionIds: ["action-save"],
    componentIds: undefined,
  },
  theme: {
    version: 1,
    pageKind: "action",
    tabIds: [
      "tab-theme-overview",
      "tab-theme-presets",
      "tab-theme-colors",
      "tab-theme-typography",
      "tab-theme-preview",
    ],
    actionIds: ["action-save", "action-publish"],
    componentIds: undefined,
  },
  header: {
    version: 1,
    pageKind: "action",
    tabIds: [
      "tab-header-mobile",
      "tab-header-style",
      "tab-header-desktop",
      "tab-header-menus",
    ],
    dialogIds: ["dialog-header-menu-item"],
    actionIds: ["action-save", "action-publish"],
    componentIds: undefined,
  },
  footer: {
    version: 1,
    pageKind: "action",
    tabIds: ["tab-footer-sections", "tab-footer-layout", "tab-footer-design"],
    dialogIds: ["dialog-footer-section"],
    actionIds: ["action-save", "action-publish"],
    componentIds: undefined,
  },
};
